### ISSUE TITLE
remove bluebird

### ISSUE THREAD

**Issue by jimmywarting** [serverless-heaven/serverless-webpack#1024]
switch it out for native promise and also use async/await

**Comment by vicary** [comment]
I tried, it requires considerable effort; especially when interlaced with tests.

You may start a PR if you want to see it sooner.

**Comment by vicary** [comment]
@jimmywarting The level of refactoring is likely to result in a major release, so I would not expect this to be done by a single person.

If you are really interested, please study the current codebase and start with an actual proposal. We can start discussion from there, I'll see what I can do and work on the same PR if needed.
