### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by edrichhans** [serverless-heaven/serverless-webpack#1031]
# This is a (Bug Report)

## Description

One of my functions is returning the error `SyntaxError: Unexpected token '.'` when I run `sls invoke local --function myFunction`. 

The stack trace is as follows:

```
SyntaxError: Unexpected token '.'
    at Object../src/util/user.js (/Users/edrichhans/Projects/containers/my-api/.webpack/runCustomNotifications/src/jobs/runCustomNotifications.js:24766:1)
    at __webpack_require__ (/Users/edrichhans/Projects/containers/my-api/.webpack/runCustomNotifications/src/jobs/runCustomNotifications.js:31588:42)
    at eval (webpack://my-api/./src/jobs/runCustomNotifications.ts?:55:72)
    at Module../src/jobs/runCustomNotifications.ts (/Users/edrichhans/Projects/containers/my-api/.webpack/runCustomNotifications/src/jobs/runCustomNotifications.js:5477:1)
    at __webpack_require__ (/Users/edrichhans/Projects/containers/my-api/.webpack/runCustomNotifications/src/jobs/runCustomNotifications.js:31588:42)
    at /Users/edrichhans/Projects/containers/my-api/.webpack/runCustomNotifications/src/jobs/runCustomNotifications.js:31655:37
    at Object.<anonymous> (/Users/edrichhans/Projects/containers/my-api/.webpack/runCustomNotifications/src/jobs/runCustomNotifications.js:31660:12)
...
```

When i went to investigate the bundled file, line `24766` had this string that could be problematic:

`sourceURL=webpack://my-api/./src/util/user.js?`

Anyone know what is causing this? it seems `./` is not a valid path param.

For bug reports:
* What went wrong? I am getting a syntax error from my bundled function
* What did you expect should have happened? The function should run without error
* What was the config you used? please see below
* What stacktrace or error message from your provider did you see? Please see above

## Additional Data

* ***Serverless-Webpack Version you're using***: ^5.6.0
* ***Webpack version you're using***: ^5.65.0
* ***Serverless Framework Version you're using***: 5.5.1
* ***Operating System***: darwin
* ***Stack Trace (if available)***:

### Webpack config
```
// webpack.config.js
const path = require('path');
const slsw = require('serverless-webpack');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  externals: ['sharp'],
  resolve: {
    extensions: ['*', '.ts', 'tsx', '.js', '.jsx'],
    alias: {
      src: path.resolve(__dirname, 'src/'),
    },
  },
  target: 'node',
  module: {
    rules: [
      {
        test: /\.(tsx?)$/,
        loader: 'babel-loader',
        exclude: [
          [
            path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, '.serverless'),
            path.resolve(__dirname, '.webpack'),
          ],
        ],
      },
    ],
  },
  plugins: [
    new CopyPlugin({
      patterns: [{ from: path.resolve(__dirname, 'assets'), to: 'assets' }],
    }),
  ],
};
```

**Comment by vicary** [comment]
Questions about general webpack usage isn't exactly related to `serverless-webpack`, closing this and you may reopen if you feel like it is related to the plugin.

The error looks like an incorrectly bundled result. The `sourceURL=` part is the source map, it should looks like `//# sourceURL=webpack://my-api/./src/util/user.js.map`. Instead it looks like the comment line is incorrectly interpreted as syntax.

I could think of two possibilities from your clues, either

1. **Build Time**: You accidentally fed a bundled js into `webpack` as an entry, and in turn `babel-loader` is the one actually throwing this.
2. **Run Time**: Your `webpack.config.js` does not define `devtool`, so the line `sourceURL=` shouldn't be there at all. It may be hinting that webpack is not using your provided config.
