### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by MRHarutyun** [serverless-heaven/serverless-webpack#1051]
# This is a Bug Report

## Description

I have a serverless application which is using differnt libs and one of them is googleapis.
When I am creating a deployable package and trying to run it I am getting "Cannot find module ./docs" which is a folder in googleapis lib and is used in that lib internally.
I have checked the generated zip file and that "docs" folder is missing but it exists by default locally.
Somehow that exact folder has being deleted in packaging process.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.5.0 and 5.6.0
* ***Webpack version you're using***: 5.37.0
* ***Serverless Framework Version you're using***: 1.83.3
* ***Operating System***: MacOs (also the same problem in aws)
* ***Stack Trace (if available)***: Error: Cannot find module './docs'
Require stack:
- /Users/harut/Documents/projects/pl-services/.serverless/prelaunch-services/node_modules/googleapis/build/src/apis/index.js
- /Users/harut/Documents/projects/pl-services/.serverless/prelaunch-services/node_modules/googleapis/build/src/googleapis.js
- /Users/harut/Documents/projects/pl-services/.serverless/prelaunch-services/node_modules/googleapis/build/src/index.js
- /Users/harut/Documents/projects/pl-services/.serverless/prelaunch-services/src/services/analytics-service/google/crons/sync.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/harut/Documents/projects/pl-services/.serverless/prelaunch-services/node_modules/googleapis/build/src/apis/index.js:99:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)

webpack.config.js

`/* eslint-disable @typescript-eslint/no-var-requires */
"use strict";

const path = require("path");
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");

const entries = {};

Object.keys(slsw.lib.entries).forEach((key) => {
  entries[key] = ["./source-map-install.js", slsw.lib.entries[key]];
});

const use = [
  { loader: "cache-loader" },
  {
    loader: "ts-loader",
    options: {
      experimentalWatchApi: true,
      happyPackMode: true,
      transpileOnly: true,
    },
  },
];

if (slsw.lib.webpack.isLocal) {
  use[2] = use[1];
  use[1] = {
    loader: "thread-loader",
    options: {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      poolTimeout: Infinity,
      workers: require("os").cpus().length - 1,
    },
  };
}

const plugins = [
  new ForkTsCheckerWebpackPlugin({ eslint: { files: "./src/**/*" } }),

  new CopyWebpackPlugin({
    patterns: ["serverless.yml"],
  }),
];

module.exports = {
  devtool: "eval-cheap-module-source-map",
  entry: entries,
  externals: [nodeExternals()],
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  module: { rules: [{ test: /\.tsx?$/, use }] },
  output: {
    filename: "[name].js",
    libraryTarget: "commonjs2",
    path: path.join(__dirname, ".webpack"),
    pathinfo: false,
  },
  plugins,
  resolve: {
    extensions: [".js", ".jsx", ".json", ".ts", ".tsx"],
  },
  stats: "minimal",
  target: "node",
};
`

**Comment by vicary** [comment]
@MRHarutyun you may try using [`forceInclude`](https://github.com/serverless-heaven/serverless-webpack#forced-inclusion) to include everything under `node_modules/googleapis`

**Comment by MRHarutyun** [comment]
@vicary  I was using node-prune library before deploying and I don't know why it was deleting that folder.
since this issue is not connected to serverless-webpack, I am closing it.
