### ISSUE TITLE
Exclude specific files per function

### ISSUE THREAD

**Issue by martinjuhasz** [serverless-heaven/serverless-webpack#1065]
# This is a Bug/Feature Request

## Description
Following scencario
```
functions/func1
 - uses dependency: a, b
functions/func2
 - uses dependency: a, b, c
 package.json:
 - dependencies: a,b,c
```
All functions get zipped into an indivual package (`individually: true`) but contain all dependencies in each of their `node_modules` folder. So even `func1.zip` includes `node_modules/c`. 

As one of my functions includes a pretty large dependency, i only want to bundle it into this one function.
Is this possible? Is their either a way to bundle only the dependencies needed for each function or to exclude specific files per function `entry`?

See also my webpack config and serverless.yaml
```
package:
  individually: true
custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: "yarn"
    includeModules:
      forceExclude:
        - aws-sdk
```
```
const path = require('path')
const slsw = require('serverless-webpack')
const nodeExternals = require('webpack-node-externals')

module.exports = {
	entry: slsw.lib.entries,
	target: 'node',
	devtool: 'source-map',
	externals: [nodeExternals()],
	mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
	resolve: {
		extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
	},
	module: {
		rules: [
			{
				test: /\.(ts|js)x?$/,
				exclude: /node_modules/,
				use: ['babel-loader'],
			},
		],
	},
	output: {
		libraryTarget: 'commonjs',
		path: path.join(__dirname, '.webpack'),
		filename: '[name].js',
	},
}

```
Thanks for any help
## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.1
* ***Webpack version you're using***: 4.41.5
* ***Serverless Framework Version you're using***: 1.63.0
* ***Operating System***: osx
* ***Stack Trace (if available)***:

**Comment by vicary** [comment]
My approach for this is to drop the packager, remove `NodeExternal` and let webpack crawls into `node_modules`, this greatly increases bundle time and resources required but currently this is the only way to properly do tree shaking for each and every single entry.

**Comment by vicary** [comment]
If you are going down this route, let me know the number of functions you are building. There are more plugins you need to add if you are hitting fd limits.

**Comment by martinjuhasz** [comment]
ok cool. thank you for all those details. i really might consider this route. Currently i'm running around 10 functions which might increase to around 100 at some later point maximum i guess.

As an alternative, might there be a way for me to specifically block one module from getting added to all functions except one? Just as a workaround for the current situation until i might redo the build pipeline.

**Comment by martinjuhasz** [comment]
is there prob. some way to hook into the steps between transpiling and zipping to run some bash command to `rm` those?

**Comment by vicary** [comment]
AFAIK I don't think there is a  one capable of running after each function. Serverless has a hook event after all functions though.

You may try `serverless-scriptable-plugin` to easily run scripts after lifecycle hook events, I vaguely remember that they have compatibility issues with serverless v3 please bare in mind.

**Comment by martinjuhasz** [comment]
ok, thanks for those recommendations. I'll take a look at all of them. 
I'm not sure if this might be something serverless-webpack might consider as a feature (as this is a weird side case) so i'll close this issue.

Thanks again!
