### ISSUE TITLE
`--watch` flag not working with serverless v3

### ISSUE THREAD

**Issue by georgediaz88** [serverless-heaven/serverless-webpack#1121]
Hi, first thanks for your awesome plugin. Updating to latest serverless in the 3.x series (v3.12.0) with latest serverless-webpack (5.6.1), I noticed `--watch` stopped working. It previously worked flawlessly using serverless 2.x.

When I run:

`serverless invoke local --function myfunction --path event.json --watch`

I then get error: 

`Detected unrecognized CLI options: "--watch".`

Having the `--watch` option work is important for productivity and great dev experience. If I don't provide a `--watch`, I'm able to successfully invoke my local function. Any ideas what might be the issue with `--watch` not working?

Thanks!
George

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.6.1
* ***Webpack version you're using***: 5.71.0
* ***Serverless Framework Version you're using***: 3.12.0
* ***Operating System***:  Apple M1 (macOS Monterey 12.2.1)
* ***Stack Trace (if available)***:

`serverless invoke local --function myfunction --path event.json --watch`

<img width="565" alt="Screen Shot 2022-04-06 at 9 28 17 PM" src="https://user-images.githubusercontent.com/667650/162108347-5b5c867c-ceb7-4ae9-b6f2-5f3470f6d89a.png">

**Comment by iaansanity** [comment]
I'm having the same issue with --webpack-use-polling
![image](https://user-images.githubusercontent.com/38838900/170664618-0e82608e-dded-455b-bc4f-6d01c63e8f8b.png)

**Comment by medikoo** [comment]
@j0k3r this option simply needs to be defined for the command, and plugins may extend existing commands with their options in same manner as they introduce new commands

**Comment by j0k3r** [comment]
@medikoo thanks, didn't notice it!
