### ISSUE TITLE
'Unable to find Webpack configuration'

### ISSUE THREAD

**Issue by JonathanMSifleet** [serverless-heaven/serverless-webpack#1178]
# This is a Bug Report

For bug reports:
* What went wrong?
Project failed to deploy
* What did you expect should have happened?
Project should deploy
* What was the config you used?
https://github.com/JonathanMSifleet/S3Drive/blob/8c44a10c62d1030b76c32880e247a9f7c221a0ab/backend/serverless.yml
* What stacktrace or error message from your provider did you see?
'Unable to find Webpack configuration' 

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.7.1
* ***Webpack version you're using***: 5.73.0
* ***Serverless Framework Version you're using***: 3.19.0
* ***Operating System***: Windows 10
* ***Stack Trace (if available)***:

**Comment by JonathanMSifleet** [comment]
Adding a lambda solves this issue
 #https://github.com/AnomalyInnovations/serverless-bundle/issues/293

**Comment by j0k3r** [comment]
Could you share some error logs, configuration, etc?

**Comment by JonathanMSifleet** [comment]
> Could you share some error logs, configuration, etc?

> PS C:\Users\jonathans\Desktop\S3Drive\backend> SET SLS_DEBUG=*
> PS C:\Users\jonathans\Desktop\S3Drive\backend> serverless deploy --verbose
> Running "serverless" from node_modules
> 
> Deploying S3Drive to stage dev (eu-west-2)
> 
> Packaging
> Using configuration:
> {
>   "webpackConfig": "./webpack.config.js",
>   "includeModules": false,
>   "packager": "npm",
>   "packagerOptions": {},
>   "keepOutputDirectory": false,
>   "concurrency": 12
> }
> Removing C:\Users\jonathans\Desktop\S3Drive\backend\.webpack
> Individually packaging with concurrency at 12 entries a time.
> [Webpack] Building with Webpack
> 
> × Stack S3Drive-dev failed to deploy (0s)
> Environment: win32, node 16.15.1, framework 3.19.0 (local) 3.18.1v (global), plugin 6.2.2, SDK 4.3.2
> Docs:        docs.serverless.com
> Support:     forum.serverless.com
> Bugs:        github.com/serverless/serverless/issues
> 
> Error:
> 'Unable to find Webpack configuration'

[Configuration can be found here](https://github.com/JonathanMSifleet/S3Drive/blob/8c44a10c62d1030b76c32880e247a9f7c221a0ab/backend/serverless.yml)

**Comment by j0k3r** [comment]
But why do you want to use `serverless-webpack` without any JS code in your folder?

**Comment by JonathanMSifleet** [comment]
> But why do you want to use `serverless-webpack` without any JS code in your folder?

I was initialising the project and wanted to deploy the stack before adding lambdas

**Comment by j0k3r** [comment]
That plugin should definitely be used with at least one NodeJS Lambda.
