### ISSUE TITLE
plugin does not set types

### ISSUE THREAD

**Issue by tetiana-fomina-photobox** [serverless-heaven/serverless-webpack#1212]
# This is a (Bug Report)

## Description

For bug reports:
I updated my serverless from 2 version to 3d version and I got error (via serverlesss doctor) that this plugin does not set types(since in serverless v3 they updated CLI commands and add 'params').
I got the error bellow:
```
 We've resigned from this deprecation in the context of v2 (it'll be re-added in the context of v3). 
We continue to advise upgrade so schema for CLI options is provided.

Internal handling of CLI arguments was improved with type awareness for options. 
Now each option definition is expected have type defined in its settings.

Possible values are string, boolean and multiple. Check Defining options documentation for more info.

If you rely on a plugin which does not set types (yet) please report the issue at its issue tracker.

Starting with v3.0.0 any option extensions which does not have type defined will be communicated with a thrown error
```

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.8.0
* ***Webpack version you're using***: 5.74.0
* ***Serverless Framework Version you're using***: 3.12.7
* ***Operating System***: macOS
* ***Stack Trace (if available)***:

**Comment by j0k3r** [comment]
Version 5.8.0 defined CLI type properly. This is weird.

Can you update to the latest version of Serverless (3.21.0 I guess) and try again?

Also, can you paste the whole command and the whole output to be sure it's related to the plugin?

Thanks

**Comment by tetiana-fomina-photobox** [comment]
yes, you are totally right! Thank you so much
