### ISSUE TITLE
Warning ⚠️ ServerlessWebpack for "webpack-use-polling" Plugins do not predefine type for introduced options

### ISSUE THREAD

**Issue by manikpokhetra79** [serverless-heaven/serverless-webpack#1217]
# This is a Warning Report.

## Description

I am getting this warning when deploying the serverless app.
 CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
   - ServerlessWebpack for "webpack-use-polling" 
   
#### Screenshot:
<img width="1098" alt="Screenshot 2022-08-05 at 9 30 42 AM" src="https://user-images.githubusercontent.com/25217510/182999601-e0602710-1c43-441f-add2-521a76e1916b.png">

## Additional Data
```
    "fork-ts-checker-webpack-plugin": "^7.2.13",
    "serverless": "^2.72.2",
    "serverless-dotenv-plugin": "^3.12.2",
    "serverless-dynamodb-local": "^0.2.40",
    "serverless-offline": "^8.4.0",
    "serverless-prune-plugin": "^2.0.1",
    "serverless-webpack": "^5.8.0",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.5.0",
    "typescript": "^4.5.5",
    "webpack": "^5.74.0",
    "webpack-node-externals": "^3.0.0"
* ***Stack Trace (if available)***:

**Comment by j0k3r** [comment]
What serverless command are you launching?

**Comment by manikpokhetra79** [comment]
> What serverless command are you launching?

`serverless deploy`

**Comment by rion18** [comment]
Same output for `serverless doctor`:

```
1 deprecation triggered in the last command:

CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
 - ServerlessWebpack for "webpack-use-polling"
Please report this issue in plugin issue tracker.
Starting with next major release, this will be communicated with a thrown error.
More info: https://serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA_V3
```

**Comment by simonramosb** [comment]
Having the same issue over here! Do you guys find out anything? 
![image](https://user-images.githubusercontent.com/64170232/185218249-7c61beff-3c34-4dca-bcaa-124cd2346181.png)

**Comment by manikpokhetra79** [comment]
> Having the same issue over here! Do you guys find out anything? ![image](https://user-images.githubusercontent.com/64170232/185218249-7c61beff-3c34-4dca-bcaa-124cd2346181.png)

No Simon. We did not find anything on this.

**Comment by manikpokhetra79** [comment]
> Hey @manikpokhetra79! We solved that issue by fixing our webpack.config.js. Start with a basic config and just add more properties to see what is the one giving you those errors.
> 
> FYI, serverless-dotenv-plugin is not required since [serverless framework already got it](https://www.serverless.com/framework/docs/environment-variables)

Thanks, @simonramosb. I'll try your way and add the update here.

**Comment by j0k3r** [comment]
Will be fixed by https://github.com/serverless-heaven/serverless-webpack/pull/1213 in v5.9.0
