### ISSUE TITLE
Webpack generating wrong symlink to package.json and node_modules on build

### ISSUE THREAD

**Issue by rafapaulin** [serverless-heaven/serverless-webpack#1236]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? Webpack is generating `node_modules` and `package.json` symlinks on build folder that points to wrong location, breaking all the modules imports on lambdas.
* What did you expect should have happened? symlink created correctly
* What was the config you used?
![image](https://user-images.githubusercontent.com/13452406/187587316-7572fbf5-dba7-4070-b02f-2dd842b6679c.png)
![image](https://user-images.githubusercontent.com/13452406/187587346-0b118f40-c7f7-41f2-82fb-737b83678cb1.png)
* What stacktrace or error message from your provider did you see?
![image](https://user-images.githubusercontent.com/13452406/187587381-f5327ba4-13c2-441d-a463-7f090bfc93b9.png)
![image](https://user-images.githubusercontent.com/13452406/187587828-2084e28d-b3ed-4242-adcf-175c25d9419d.png)
these symlinks should be valid. (point to  `/home/rafapaulin/lab/Valtech/elastic-platform/{node_modules|package.json}`)

same error on aws cloudwatch
![image](https://user-images.githubusercontent.com/13452406/187588248-467dd479-4025-4904-8355-fb0d38929063.png)

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us. N/A
* If there is additional config how would it look N/A

Similar or dependent issue(s): N/A

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.9.1
* ***Webpack version you're using***: 5.74.0
* ***Serverless Framework Version you're using***: 3.19.0
* ***Operating System***: linux
* ***Stack Trace (if available)***:

This happens on both deploying and running lambdas locally

**Comment by vicary** [comment]
@rafapaulin Hi, thanks for reporting. I don't think I understand the issue, because if it's only an incorrect symlink the required module should not be `'undefined'` and `''`.

Would you mind sharing a more detailed reproducing steps or a minimum reproducing repo?
