### ISSUE TITLE
Support for multi-compiler [Webpack 2]

### ISSUE THREAD

**Issue by logicalicy** [serverless-heaven/serverless-webpack#124]
Perhaps one for the future –

To create separate output filename patterns, using separate configs with [Webpack's multi-compiler](https://github.com/webpack/webpack/tree/master/examples/multi-compiler) comes in handy.

When attempting to use this Webpack feature, we see:

```
TypeError: Cannot read property 'errors' of undefined
    at BbPromise.fromCallback.then.stats (<PATH_TO_PROJECT>/node_modules/serverless-webpack/lib/compile.js:24:30)
```

While only single configs are supported currently, I thought to add here to track possible future support for multiple configs.

**Comment by HyperBrain** [comment]
This is related to #120 . If we'd support optimal individual packaging with separate tree-shaking and optimization per lambda function, multi-compiler support is a must.

So this will be handled as an implementation step there, with the first approach being automatic configuration as soon as you enable individual packaging.

**Comment by HyperBrain** [comment]
I've prepared the plugin's infrastructure to support manual multi-compile scenarios with a subsequent implementation in #177 . As soon as we're on v3, we can take care of this.

**Comment by HyperBrain** [comment]
@logicalicy Is this still an issue? With all the improvements done in V3, especially the `slsw.lib` objects you now have full access to the serverless environment and can create a single webpack config that configures itself by evaluating that state.
Additionally, for individual packaging multi-compile is now automatically enabled, to let Webpack optimize every single function separately.

**Comment by HyperBrain** [comment]
I'll close this now as there were no responses for a long time. Feel free to revive the discussion if needed.

**Comment by taschmidt** [comment]
Hey there, I just ran across this issue.  I have a serverless project with multiple server-side bundles (lambdas) but now I need to put together a client-side bundle.  Without support for multiple configs (i.e. one "node" and one "web"), how am I supposed to do this?
