### ISSUE TITLE
Webpack doesn't respect --package flag when using deploy command

### ISSUE THREAD

**Issue by eclecticjohny** [serverless-heaven/serverless-webpack#1317]
## Description

We have found that while webpack works with the ‘serverless package’ command and creates a package, when we do the ‘serverless deploy --package package.zip’ command instead of using previously created package.zip webpack re-runs and generates a new bundle. Is there a way to stop webpack from trying to bundle again when using the --package flag with the serverless deploy commmand?

## Additional Data

* ***Serverless-Webpack Version you're using***: "serverless-webpack": "^5.10.0"
* ***Serverless Framework Version you're using***: "serverless": "^3.24.0"
* ***Operating System***: MacOS 12.5.1

**Comment by vicary** [comment]
Tested with the typescript example, webpack doesn't seen to run when `--package` options is set.

@eclecticjohny Would you please share your logs, or something from your deploy that shows webpack is running?
