### ISSUE TITLE
Allow generating ES Module (ESM) output from npm

### ISSUE THREAD

**Issue by aldenquimby** [serverless-heaven/serverless-webpack#1493]
# This is a (Bug Report / Feature Proposal)

## Description
- I'd like to generate an ESM output so that I can leverage top-level await and provisioned concurrency to load secrets during lambda initialization, [as described by this AWS blog post](https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/)
- Here the relevant part of my `serverless.yml`
```yml
provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    webpackConfig: 'webpack.config.cjs'
    includeModules: true
```
- My `package.json` includes `"type": "module"`
- And my `webpack.config.cjs` (CJS b/c `serverless-webpack` doesn't support an ESM `webpack.config.js`, but that's a separate issue):
```js
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

const { isLocal } = slsw.lib.webpack;

module.exports = {
  entry: slsw.lib.entries,
  mode: isLocal ? 'development' : 'production',
  target: 'node18',
  externals: [nodeExternals({ importType: 'node-commonjs' })],
  externalsPresets: { node: true },
  externalsType: 'node-commonjs',
  module: {
    rules: [{
      test: /\.ts$/,
      use: [{ loader: 'ts-loader', options: { transpileOnly: true } }],
      exclude: /node_modules/,
    }],
  },
  resolve: {
    extensions: ['.ts', '.js'],
    modules: ['node_modules', path.resolve(__dirname, './src')],
  },
  experiments: { outputModule: true },
  output: {
    library: { type: 'module' },
    path: path.join(__dirname, '.webpack'),
    module: true,
  },
};
```
- This works, but it produces `[name].mjs` outputs, [which breaks `serverless-offline`](https://github.com/serverless/serverless/issues/11308) 
- So I set my webpack `output.filename` to `[name].js` and then local / `serverless-offline` works again!
- But now deployed code fails b/c Lambda doesn't know this is an ESM output
- Specifically, the `package.json` generated by `serverless-webpack` is missing the `"type": "module"` that I set as my project default

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.11.0
* ***Webpack version you're using***: 5.85.1
* ***Serverless Framework Version you're using***: 3.32.2
* ***Operating System***: macOS Ventura 13.3.1

**Comment by adperossa** [comment]
Any news about the proposed fix? I'm currently dealing with this, I'd love to use webpack because the bundle sizes are quite smaller, but I have to choose either using esm or webpack for the packaging. Thanks for the effort!

**Comment by aldenquimby** [comment]
@adperossa I believe @vicary wants to wait for @j0k3r to code review #1495 before shipping it

I've confirmed the change works for my company, we're now using a fork in production that has the change
