### ISSUE TITLE
V3 pre-release available (3.0.0-rc.2) on NPM

### ISSUE THREAD

**Issue by HyperBrain** [serverless-heaven/serverless-webpack#187]
# V3 is available as prerelease now!

To use it you have to set it explicitly in your package.json as `^3.0.0-rc.1`. This will update automatically for next rc releases or the final release.

For the release notes see [here](https://github.com/elastic-coders/serverless-webpack/releases/tag/v3.0.0-rc.1)

**Comment by HyperBrain** [comment]
Referencing all affected issues/PRs:
#116 #117 #120 #151 #152 #173 #179 #185 #186

**Comment by HyperBrain** [comment]
Forgot #134 #135

**Comment by HyperBrain** [comment]
Published 3.0.0-rc.2 containing issues #145 #191 #199 #195

**Comment by jayair** [comment]
Looking forward to it. Thanks for all the hard work!

**Comment by HyperBrain** [comment]
V3 has been officially released! https://github.com/serverless-heaven/serverless-webpack/releases/tag/v3.0.0

Closing this now.
