### ISSUE TITLE
Serverless 4 Support

### ISSUE THREAD

**Issue by jiteshmanglani** [serverless-heaven/serverless-webpack#1923]
# This is a Bug Report

## Description

For bug reports:
* Can't install packages due to unresolved dependency
* It should install all the packages
* normal config
* `npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: serverless-webpack@5.14.1
npm ERR! Found: serverless@4.2.4
npm ERR! node_modules/serverless
npm ERR!   dev serverless@"^4.2.4" from the root project
npm ERR!   peer serverless@">=2.60" from serverless-domain-manager@7.4.0
npm ERR!   node_modules/serverless-domain-manager
npm ERR!     dev serverless-domain-manager@"^7.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer serverless@"1 || 2 || 3" from serverless-webpack@5.14.1
npm ERR! node_modules/serverless-webpack
npm ERR!   dev serverless-webpack@"^5.14.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: serverless@3.39.0
npm ERR! node_modules/serverless
npm ERR!   peer serverless@"1 || 2 || 3" from serverless-webpack@5.14.1
npm ERR!   node_modules/serverless-webpack
npm ERR!     dev serverless-webpack@"^5.14.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
`

Similar or dependent issue(s):
* NA

## Additional Data

* ***Serverless-Webpack Version 5.14.1***:
* ***Webpack version 5.93.0***:
* ***Serverless Framework Version 4.2.4 ***:
* ***Operating System Fedora 39***:

**Comment by j0k3r** [comment]
I checked quickly and it seems the v4 file structure completely changed.

v4 only expose the binary and that's all: https://www.npmjs.com/package/serverless?activeTab=code
v3 exported usefull stuff that we are using internally: https://www.npmjs.com/package/serverless/v/3.39.0?activeTab=code

Maybe it needs a better check to see if we can find a workaround.

**Comment by vicary** [comment]
I've sent an email to Serverless, hopefully we get a reply soon.

**Comment by vicary** [comment]
@jiteshmanglani Unfortunately no responses are received thus far.

**Comment by kevinlbatchelor** [comment]
I pinged them on the slack channel, no response

**Comment by vicary** [comment]
Just received this reply via email, full response quoted below.

> Hi Vicary,
> 
> Apologies for the slow reply. As you can imagine we have been quite busy.
> 
> As to your question, really the only standard requirement on our side is to ensure that the npm dependancies point to serverless@4 and not v3 anymore. If there is anything else that comes up as an issue, I would recommend adding an issue on the project GitHub as that will allow everyone on the engineering team the opportunity to see the issue publicly and work with you from there: https://github.com/serverless/serverless/issues

**Comment by j0k3r** [comment]
Support has been added in [5.15.0](https://github.com/serverless-heaven/serverless-webpack/releases/tag/v5.15.0)

**Comment by jiteshmanglani** [comment]
Thanks :+1:
