### ISSUE TITLE
V3 fails to deploy compiled code. Instead deploys whole source

### ISSUE THREAD

**Issue by rallu** [serverless-heaven/serverless-webpack#249]
# This is a Bug Report

## Description

After updating from 2.3.3 to 3.1.0 (and 3.1.1) deployed package contains whole source tree instead of the compiled result from webpack.

Downgrading to 2.3.3 fixed problem again. Developing in localhost works as intended in 3.1.0.

My webpack.config.js:
```
const path = require('path');
const slsw = require('serverless-webpack');

module.exports = {  
  entry: slsw.lib.entries,
  target: 'node',
  devtool: 'nosources-source-map',
  module: {
    loaders: [
      { test: /\.ts(x?)$/, loader: 'ts-loader' }
    ]
  },
  resolve: {
    extensions: ['.ts', '.js', '.tsx', '.jsx']
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
    sourceMapFilename: '[file].map'
  },
};
```

## Additional Data

* ***Serverless-Webpack Version you're using***: 3.1.0
* ***Webpack version you're using***: 3.4.1
* ***Serverless Framework Version you're using***: 1.16.1
* ***Operating System***: Mac OSX
* ***Stack Trace (if available)***:

**Comment by HyperBrain** [comment]
Hi @rallu , thanks for asking 🙌 

this is most likely a configuration issue with your function definitions in your `serverless.yml`. Please make sure that the handlers of the functions are declared correctly and include the relative paths to the handlers (e.g. `handler: src/mydir/myfunc.handler`).

Could you post the function definitions? Your `webpack.conf.js` looks ok so far.

Additionally you should use the new `module: rules: ...` syntax to specify the loaders in case you use webpack 2+ (they changed that from webpack 1.x to 2.x).

**Comment by HyperBrain** [comment]
Just came into my mind: I saw you use Serverless 1.16. It also could be an issue with versions <1.18. Would you mind to try with a recent framework version? We had such an issue in #206 .

**Comment by rallu** [comment]
Hey, 

Thanks! It was the serverless version issue. I updated to 1.23 and now it works perfectly. And thanks for the `module: rules` hint. I copy pasted typescript example from your repository so I recommend that you update it there too :)

**Comment by HyperBrain** [comment]
@rallu Glad to hear that it is the version. I'll add a hint in the docs (supporting that old SLS versions only adds efforts 😄 without worth).

You're right, the examples might need some small corrections to be up to date again. Thanks for the hint.
