### ISSUE TITLE
Use stats option to overwrite console.log behaviour

### ISSUE THREAD

**Issue by dangcuuson** [serverless-heaven/serverless-webpack#260]
# This is a Feature Proposal
## Description
Currently, the stats options in webpack.config.js seems to be ignored. No matter what I put in my webpack.config.js, the console output is the same, which I find them too verbose and annoying, especially when developing & watch. E.g: 

![image](https://user-images.githubusercontent.com/20551609/32031806-1ad97ddc-ba4f-11e7-9428-481e25f0c62a.png)

I think it would be good if we can allow webpack stats config to overwrite the default behaviour.

[Update] 
After digging through the source, I think the we can do it easily by updating [lib/compile.js](https://github.com/serverless-heaven/serverless-webpack/blob/5c9f14d53f4ce739ebcf69748d532c0f5253b7c3/lib/compile.js#L24)
and [lib/wpwatch.js](https://github.com/serverless-heaven/serverless-webpack/blob/5c9f14d53f4ce739ebcf69748d532c0f5253b7c3/lib/wpwatch.js#L25)

I can make a PR if you're ok with this.

Similar or dependent issue(s):
* Can't find any

## Additional Data

* ***Serverless-Webpack Version you're using***: 3.1.2
* ***Webpack version you're using***: 3.8.1
* ***Serverless Framework Version you're using***: 1.23.0

**Comment by HyperBrain** [comment]
Hi @dangcuuson , thanks for the thoughts.

you're absolutely right that the stats output currently is not configurable and the two locations are the right place to have a possible configuration in (there is a 3rd one at [run/watch](https://github.com/serverless-heaven/serverless-webpack/blob/master/lib/run.js#L20) that is used on `serverless invoke local --watch` but there the output is disabled completely).

I think we can let the default be as it is now (i.e. print the whole data if nothing else is specified), but if overridden in the config, that should be used.

The approach to let the [stats config option](https://webpack.js.org/configuration/stats/) override our defaults sounds good to me. I'm happy if you do a PR for the issue 😃

**Comment by HyperBrain** [comment]
Released with [`serverless-webpack@4.0.0`](https://github.com/serverless-heaven/serverless-webpack/releases/tag/v4.0.0)
