### ISSUE TITLE
Get environment/stage in webpack.config.js?

### ISSUE THREAD

**Issue by tommedema** [serverless-heaven/serverless-webpack#301]
Is it possible to retrieve the serverless stage or environment in webpack.config.js, or to load different config files for different environments?

When I add this to webpack.config.js:

```
console.log(`bundling with webpack for environment ${process.env.NODE_ENV}`)
```

It turns out that `NODE_ENV` is undefined.

**Comment by HyperBrain** [comment]
Hi @tommedema ,
you can retrieve the serverless stage within the webpack config:
```js
const stage = slsw.lib.options.stage;

// You also have access to the whole Serverless service object too:
const serverless = slsw.lib.serverless;
```
So, in fact, you can access anything that is available in the serverless instance,
just like any plugin.

**Comment by tommedema** [comment]
Excellent!
