### ISSUE TITLE
Don't redeploy when files does not changed

### ISSUE THREAD

**Issue by pavelvlasov** [serverless-heaven/serverless-webpack#311]
# This is a Bug Report / Feature Proposal

## Description

When using serverless-webpack service gets redeployed even if cloud-formation template was not changed and source files remain untouched.

Proposal is to save and check [output hash](https://webpack.js.org/guides/caching/#output-filenames) and don't trigger deploy if it has the same value.

Would love to jump on that, just need a bit of a guidance on how to better implement this.

**Comment by HyperBrain** [comment]
Hi @pavelvlasov , the deployment is done by Serverless, not the plugin. As long as the created output files in `.serverless` are the same, Serverless should not upload the artifacts again.
The plugin only does the compilation in a deterministic way, so, if no sources nor anything in your `serverless.yml` changes, the zip files created for the service or the functions are the same.

Can you check if _really_ nothing changed? E.g. if you do not use a package-lock file to lock your dependencies to a specific version, any dependency update _will_ of course end up with a different package -> and thus it is redeployed.

**Comment by pavelvlasov** [comment]
thanks for clarification @HyperBrain, that might be a problem with one of the loaders. Will try to make a smaller test case to verify that. Closing for now

**Comment by juanpablovega** [comment]
Same problem here.
Spending 1-2 minutes uploading a package and updating a stack when no changes happened (running sls deploy back to back).
