### ISSUE TITLE
Invoke without building

### ISSUE THREAD

**Issue by sime** [serverless-heaven/serverless-webpack#341]
# This is a Feature Proposal

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
We test our functions by running `sls invoke local --function blah` in CI. It is one of our slowest parts of pipeline. It would be ideal if it could be built once and flagged not to build again.

```
sls webpack
sls invoke local --function blah1 --noBuild
sls invoke local --function blah2 --noBuild
```

Similar or dependent issue(s):
* n/a

## Additional Data

* ***Serverless-Webpack Version you're using***: 4.1.0
* ***Webpack version you're using***: 3.8.1
* ***Serverless Framework Version you're using***: 1.25
* ***Operating System***: OS X/Linux

**Comment by sime** [comment]
Same query on Serverless forums: https://forum.serverless.com/t/invoke-serverless-function-and-skip-a-plugin-webpack/3805

**Comment by HyperBrain** [comment]
Hi @sime . I agree, especially in a CI context the pattern is 1 * build, n * invoke. So, a single compile would make sense and a switch to disable building explicitly on all subsequent invokes.

This is related to #288 and might solve this too.

**Comment by HyperBrain** [comment]
PR available for testing. Use `"serverless-webpack": "github:serverless-heaven/serverless-webpack#skip-build-with-invoke-local"`

**Comment by HyperBrain** [comment]
@sime Do you have any chance to test the PR?

**Comment by sime** [comment]
@HyperBrain We run our CI on Travis and just tested it. CI time is now 2 minutes faster!
