### ISSUE TITLE
Node AddOns (C++ Extensions) are not loaded with node-loader

### ISSUE THREAD

**Issue by ewindisch** [serverless-heaven/serverless-webpack#359]
# This is a (Bug Report / Feature Proposal)

## Description

Developers importing dependencies that utilize native compiled code (Node Addons aka C++ Extensions) need the node-loader properly configured in order to webpack correctly.

It would be a cleaner and easier developer experience if these modules were packaged with the node-loader by default.

**Comment by HyperBrain** [comment]
Hi @ewindisch ,

Could you elaborate on how you would see the feature and what exact problem it solves a bit? Imo, the loader configurations are user-space elements that are heavily dependent on the projects and also need knowledge about the used native modules. Maybe I miss the details here 😄

**Comment by HyperBrain** [comment]
@ewindisch Could you please answer my question above? Thanks.

**Comment by HyperBrain** [comment]
I'll close this now. We can reopen it again, as soon as there is more detailed information about what this feature request should do and how this could be achieved then.
