### ISSUE TITLE
Cannot access event.queryStringParameters[ ... ][ ... ] 

### ISSUE THREAD

**Issue by causingchaos2** [serverless-heaven/serverless-webpack#362]
I believe i'm having issues with this topic as well.. How do you access queryStringParameter?, if I remove the extra JSON argument in the call to API.get it works perfect! I'm just trying to figure out if this is indeed a problem with AWS amplify and how i'm sending the JSON parameter. Thank you in advance if you can push me in the correct direction.

My client side code (aws-amplify 0.2.11 ):
`return API.get('trips','/days', {'queryStringParameters': {'param1': "99b60260-363c-11e8-b7ca-250a890d0675"}})`

My API side code ( using serverless-webpack v 1.6.0, aws sdk v 2.202.0 ) :
serverless.yml file :

```
listDays:
        handler: listDays.main
        events:
          - http:
              path: days
              method: get
              cors: true
              authorizer: aws_iam

```
API-javascript listDays.js code trying to access the event, the event.queryStringParameter.param1 just causes an error because it's null:

```
export async function main(event,context,callback) {

    const params = {
        TableName: "DAYS",

        KeyConditionExpression: "tripId = :tripId",
        ExpressionAttributeValues: {
            ":tripId": event.queryStringParameters.param1
        }
    }

  //console.log(data.tripId)
    try {
        //result will return an array of trips
        const result = await dynamoDbLib.call("query", params)
        callback(null, success(result.Items))
    } catch (e) {
        callback(null, failure({status: false}))
    }
}
```

**Comment by HyperBrain** [comment]
Hi @causingchaos2 ,

it looks like the API URL is not called with any query parameters, thus `event.queryStringParameters` is set to null. Did you try to call the url manually including the `param1` parameter with Postman?
Anyway, you should not use `queryStringParameters` without checking it for `null` first, because it is optional and can be `null` if no parameters are coming in.
I did not use `aws-amplify` anywhere in my projects, so I cannot tell if there is something there that has to be regarded.
@serverless-heaven/serverless-webpack-contributors Anyone of you has experience with `aws-amplify`?

**Comment by causingchaos2** [comment]
I appreciate the response on the matter, I figured if the object was null and requires to be accounted for in the code, I will implement that.  However, as you have said this is an open issue using the aws amplify library, and indeed assigning a queryStringParameters JSON object will result in null being assigned for event.queryStringParameter. 
I would like to report that, doing this works perfect with AWS amplify, you can access the body no problem, by doing this: 
```
API.post('trips', '/days', { body: { content: "this is some text', imageURL: 'image-s3-url' } } )

then on the other side using serverless-webpack, you can simply parse the variables out by doing; 
const data = JSON.parse(event.body)
console.log(data.content)
console.log(data.image-s3-URL)
```
But it doesn't work when passing through API.get , sending a body JSON object, or queryStringParamteter JSON object. So I can confirm my API i've designed does work, when not including a JSON argument in the aws-amplify API.get( api name, path), frustrating! Going to keep my eyes peeled on this and hopefully it's added by a kind programmer :)

However I do have a follow up question, I guess mostly to do with the serverless-webpack side, suppose I do the work around mentioned in one of the aws-amplify forums and just attach query parameters the traditional way (to the URL path), like so:

On the Client side, calling the Lambda from react code using aws-amplify.
`return API.get( 'trips' , `/days?param1=${value1}&param3={value2}`  ) `

On the server side:
serverless.yml:
```
listDays:
        handler: listDays.main
        events:
          - http:
              path: days
              method: get
              cors: true
              authorizer: aws_iam
```
Inside listDays.js:

How do I access the path variables? do I need to add anything to my serverless.yml file to indicate there is incoming parameters on the path?? i.e. how do I get the path param 1, or param 2 out of the path on this side?

export async function main(event,context,callback) {

    const params = {
        TableName: "DAYS",

        KeyConditionExpression: "tripId = :tripId",
        ExpressionAttributeValues: {
            ":tripId": event.queryStringParameters.param1
        }
    }

  //console.log(data.tripId)
    try {
        //result will return an array of trips
        const result = await dynamoDbLib.call("query", params)
        callback(null, success(result.Items))
    } catch (e) {
        callback(null, failure({status: false}))
    }
}

Thx ! been working at this for many many hours, looking forward to getting my head around it.

**Comment by franciscocpg** [comment]
hi @causingchaos2 
About your question, I think it's all answered here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html#api-gateway-proxy-integration-lambda-function-nodejs

AFAIK you don't have to change nothing in your `serverless.yml`.

**Comment by causingchaos2** [comment]
Thank you very much @franciscocpg

**Comment by causingchaos2** [comment]
For any amature coder like myself:
Because appending a JSON object queryStringParamaters is currently not implemented yet, Calling using AWS-amplify, on the client code side by appending to URL: 

`return API.get('trips',`/days?param1=${this.props.tripId}`)`

API-side Node.js code: serverless yml file:
```
listDays:
        handler: listDays.main
        events:
          - http:
              path: days
              method: get
              cors: true
              authorizer: aws_iam
```

you access param1 by doing the following, also in the API-side Node.js code:
```
if (event.queryStringParameters !== null && event.queryStringParameters !== undefined) {
        if (event.queryStringParameters.param1 !== undefined &&
          event.queryStringParameters.param1 !== null &&
          event.queryStringParameters.param1 !== "") {
          console.log("Received proxy: " + event.queryStringParameters.param1);
          tripId = event.queryStringParameters.param1;
        }
      }
```
