### ISSUE TITLE
Update doc: over at serverless-secrets

### ISSUE THREAD

**Issue by bebbi** [serverless-heaven/serverless-webpack#387]
This is a minor one.
On https://github.com/trek10inc/serverless-secrets (README), I think the most current `serverless-webpack` config just requires changing

    webpackIncludeModules

to

    webpack:
      includeModules:
        forceExclude:
          ...etc

but I thought it's better to check back here first.

**Comment by HyperBrain** [comment]
@bebbi Exactly 😄 . I optimized the previously spread configuration into one webpack hive. This should be used since version 5.x.x. Using the old configuration location will emit a warning.
