### ISSUE TITLE
unable to import ***

### ISSUE THREAD

**Issue by JTOracle** [serverless-heaven/serverless-webpack#392]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
Missing external module dependencies. 
* What did you expect should have happened?
Package all sub dependencies of my packages so that my package can be used
* What was the config you used?
service: api
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: us-west-2
  role: ...
  timeout: 30
  apiKeys: 
    - apiKey-${opt:stage, 'local'}
custom:
  webpackIncludeModules:
    forceInclude:
      - request
      
functions:
  # Mobile Logi
  mobileLogin: 
    handler: src/functions/mobile/auth/login.default
    role: ...
    events: 
      - http:
          path: auth/mobile/login
          method: post
          private: true
package: 
  exclude:
    - .gitignore
    - .git/**
    - .vscode/**
plugins:
  - serverless-offline
  - serverless-webpack
* What stacktrace or error message from your provider did you see?
{
    "errorMessage": "Cannot find module 'underscore'",
    "errorType": "Error",
    "stackTrace": [
        "Function.Module._load (module.js:474:25)",
        "Module.require (module.js:596:17)",
        "require (internal/module.js:11:18)",
        "Object.<anonymous> (/var/task/node_modules/promisified-request/promisified-request.js:4:9)",
        "Module._compile (module.js:652:30)",
        "Object.Module._extensions..js (module.js:663:10)",
        "Module.load (module.js:565:32)",
        "tryModuleLoad (module.js:505:12)",
        "Function.Module._load (module.js:497:3)"
    ]
}
--------------------------------------------------------------------
START RequestId: db212513-5643-11e8-8795-89af9e1694c3 Version: $LATEST
Unable to import module 'src/functions/shows/create': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/node_modules/promisified-request/promisified-request.js:4:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
END RequestId: db212513-5643-11e8-8795-89af9e1694c3
REPORT RequestId: db212513-5643-11e8-8795-89af9e1694c3	Duration: 3.38 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 37 MB
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):
* #12345

## Additional Data

* ***Serverless-Webpack Version you're using***:
* ***Webpack version you're using***:
* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace (if available)***:

**Comment by HyperBrain** [comment]
Hi @JTOracle , thanks for reporting.

This looks quite strange, because promisified-request explicitly has underscore as dependency, so any `npm install promisified-request` must also install underscore.

```
"dependencies": {
    "when": "2.7.x",
    "request": "2.30.x",
    "promisifier": "latest",
    "underscore": "1.6.x"
  },
```

Can you do a `serverless package --verbose`, check the output while packaging and inspect the contents of the zip files created in `.serverless` which modules they contain? Additionally, it would be good to know which version of `serverless-webpack` you are using.

**Comment by JTOracle** [comment]
I actually got it to work by including this in my config: 
```

custom:
  webpackIncludeModules:
    forceInclude:
      - request
      - underscore
```

Don't know if that is the right way to do it, but it fixed my problem. This can be closed.

**Comment by HyperBrain** [comment]
Yes, this is a perfectly valid workaround. However, I will check the `promisified-request` module as dependency with a small test project as soon as I've some spare time. I'm really curious why this happens with this dependency 😄 .

**Comment by HyperBrain** [comment]
Iw ill close this now, but report any findings in here,
