### ISSUE TITLE
Support --no-build for package` and `deploy

### ISSUE THREAD

**Issue by chrissimon-au** [serverless-heaven/serverless-webpack#398]
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

When using yarn workspaces, it's common for a service to depend on modules that are contained within the workspace.  In a CI/CD process, we would like to execute a test/build step which produces a deployable artifact (e.g. a zip of the service folder) which can be promoted through various environments.  At deploy time, the deployable artifact will not exist within the 'workspaces' structure, so yarn/npm and thus webpack are unable to locate some of the dependencies.

If `serverless deploy` supported a `--no-build` option, then we could do:

1. `serverless webpack`
1. zip folder
1. unzip in prep for deployment to an environment
1. `serverless deploy --no-build -stage qa` - this should package and deploy the serverless service using the existing `.webpack` contents

* If there is additional config how would it look

N/A

Similar or dependent issue(s):
* https://github.com/serverless/serverless/issues/352 - In reality, this proposal is really only useful due to serverless's deployment model - if this serverless issue were completed, then it would make this option unnecessary, as the output of `serverless package` would then be deployable to any given environment.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.1.5
* ***Webpack version you're using***: 4.8.1
* ***Serverless Framework Version you're using***: 1.27.2
* ***Operating System***: linux
* ***Stack Trace (if available)***: none

**Comment by kushanson** [comment]
serverless already supports "--package" option for the "deploy" command. It would make sense for serverless-webpack plugin to be smart when it sees "--package" option and not execute a webpack workflow in this case. 

I currently use serverless-webpack to package a '.serverless' folder and then I want to deploy that folder in my release process and there is no need for serverless webpack to do anything at this point in the workflow.

I went ahead and logged a feature request for what I have outlined above:
https://github.com/serverless-heaven/serverless-webpack/issues/546

**Comment by beanaroo** [comment]
Having the `--no-build` option would be very useful for deploying when specifying `--artifact` as opposed to `--package`

We are employing the approach outlined in [this article](https://medium.com/@bishwash.aryal/serverless-framework-build-immutable-package-for-ci-cd-pipeline-949b49f7df91), for more information.

Currently, removing the plugin from `serverless.yml` serves as a workaround.

**Comment by j0k3r** [comment]
This will be available in 5.4.0

**Comment by HarshRohila** [comment]
I tried release/5.4.0 branch
--no-build option gives error 'No matching handler found for 'src/handlers/handler' in '<my working dir>'

Steps
1. Clone aws-nodejs-typescript template https://github.com/serverless/serverless/tree/master/lib/plugins/create/templates/aws-nodejs-typescript
2. npm install and install release/5.4.1 of serverless webpack
3. sls webpack (creates .zip file in .webpack, with dependencies and service directories)
4. copy .webpack and package.json and serverless.ts in new directory
5. npm i && sls deploy --no-build

Throws error 'No matching handler found for 'src/handlers/handler' in '<my working dir>'
SLS_DEBUG shows webpack validate step throwing that error

**Comment by HarshRohila** [comment]
I tried release/5.4.0 branch
--no-build option gives error 'No matching handler found for 'src/handlers/handler' in 'my working dir'

Steps
1. Clone aws-nodejs-typescript template https://github.com/serverless/serverless/tree/master/lib/plugins/create/templates/aws-nodejs-typescript
2. npm install and install release/5.4.1 of serverless webpack(npm i -D git://github.com/serverless-heaven/serverless-webpack#release/5.4.0)
3. sls webpack (creates .zip file in .webpack, with dependencies and service directories)
4. copy .webpack and package.json and serverless.ts in new directory
5. npm i && sls deploy --no-build

Throws error 'No matching handler found for 'src/handlers/handler' in 'my working dir'
SLS_DEBUG shows webpack validate step throwing that error

**Comment by j0k3r** [comment]
That branch does not exist anymore. Use master instead

**Comment by HarshRohila** [comment]
> That branch does not exist anymore. Use master instead

https://github.com/serverless-heaven/serverless-webpack/tree/release/5.4.0
I used this branch, also I can see changes of the fix done for this
master branch also giving same error

As per @beanaroo suggestion, I added a workaround for removing this plugin from `serverless.ts`
Workaround is working fine

**Comment by j0k3r** [comment]
Oh yeah, the branch still exists (sorry). But it's no more up to date with the upcoming 5.4.0.
I didn't removed it to avoid breaking stuff but it's now outdated.
