### ISSUE TITLE
Add specific import to all generated lambda-functions

### ISSUE THREAD

**Issue by mcongy** [serverless-heaven/serverless-webpack#401]
# This is a Feature Proposal

## Description

Hello,
This might be more webpack related than serverless-webpack related. If so, feel free to close this.

Is it possible to include a specific import to all generated lambda-functions?
I have to include 'source-map-support/register' into all functions in order to get source maps working.

This (in my oppinion) creates a lot of unnecessary imports and can lead to problems if I forget to import it in a particular file.

Or is there any other better solution to make sourcemaps work?

Thanks!

**Comment by HyperBrain** [comment]
Hi @mcongy , you can use the `source-map-support` webpack plugin and just configure it for the babel plugin.
```
      "plugins": [
        "source-map-support"
      ]
```

Just make sure that you have the `source-map-support` module in your dependencies and the `babel-plugin-source-map-support` in your devDependencies. It will automatically add it.

**Comment by HyperBrain** [comment]
Additionally #397 is in progress right now and will allow adding arbitrary modules to the webpack entries. This will be a second approach for anyting else than source-map-support.

**Comment by HyperBrain** [comment]
Closing this. The progress of the feature is tracked by #397
