### ISSUE TITLE
Docker-Lambci Packaging of external native modules

### ISSUE THREAD

**Issue by heri16** [serverless-heaven/serverless-webpack#402]
We need an feature to run npm rebuild/install inside of a docker lambci container, during the includeModules step.
Only so will the right native binaries be built.

**Comment by HyperBrain** [comment]
Hi @heri16 , this is already available. See https://github.com/serverless-heaven/serverless-webpack/issues/342#issuecomment-383248835 for an example where the gprc library is rebuilt for the correct node version and target operating system.

**Comment by HyperBrain** [comment]
@heri16 Did you try the script feature?

**Comment by hassankhan** [comment]
Hi @heri16, closing this issue since there is a documented workaround. Please let us know if the issue persists and we can re-open it 😉

**Comment by FelschR** [comment]
The script doesn't seem to work for node-canvas.
