### ISSUE TITLE
WARNING: More than one matching handlers found for 'handler'. Using 'handler.js'.

### ISSUE THREAD

**Issue by DeX3** [serverless-heaven/serverless-webpack#405]
# This is a Bug

Since I've added `serverless-webpack` to my setup, I get the following warnings (everything still works as expected, though):
```
WARNING: More than one matching handlers found for 'handler'. Using 'handler.js'.
WARNING: More than one matching handlers found for 'handler'. Using 'handler.js'.
WARNING: More than one matching handlers found for 'handler'. Using 'handler.js'.
```

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless-Webpack Version you're using***: `^5.1.5`
* ***Webpack version you're using***: `^3.8.1`
* ***Serverless Framework Version you're using***: `1.27.3`
* ***Operating System***: Mac OS X 10.13.4

**Comment by HyperBrain** [comment]
Hi @DeX3 ,

can you check if the directory, that contains the `handler.js` file contains other files that match `handler.*`?

**Comment by DeX3** [comment]
Ah yes, I've got `handler.test.js` from the example. I guess it's not related to `serverless-webpack` then - sorry about that.

You don't happen to know if I that `handler.*`-glob is configurable somewhere?

**Comment by HyperBrain** [comment]
Currently you cannot configure the glob. But we could exclude everything like `.*\.test.\.*` from the sanity checks. Then it would automatically ignore any test files located in the handler directory.

**Comment by DeX3** [comment]
But is this glob coming from serverless or from serverless-webpack?

**Comment by HyperBrain** [comment]
From sls-webpack. It is the sanity check for the handler detection (e.g. you could have a `*.ts` and  `*.js` file and the warning tells you that the automatic resolution was triggerred for that case).

**Comment by nbransby** [comment]
What if you do have ts and js files and you want it to ingore the ts files?

**Comment by taschmidt** [comment]
@HyperBrain I'm running into the same issue, is there a way I can tell it to ignore my *.test.js files?

**Comment by ckappelhoff** [comment]
I'm running into the same issue and I don't like to move the test files into a `__tests__`-folder, just because serverless get confused with the `.test.js`-files.

Is there a way to tell serverless, just to look for `<handler>.js` and not for `<handler>.*`?
Would be nice.

**Comment by HyperBrain** [comment]
@taschmidt Feel free to open a feature request to add file patterns to a handler lookup exclude list

**Comment by ezraamos** [comment]
> What if you do have ts and js files and you want it to ingore the ts / js.map files?



> What if you do have ts and js files and you want it to ingore the ts / js.map files?

have you able to do ths?
