### ISSUE TITLE
Invalid ES6 code produced

### ISSUE THREAD

**Issue by apokryfos** [serverless-heaven/serverless-webpack#409]
# This is a Bug report

## Description
I have encountered an issue with code:

```
const config = {
    logLevel: 'i'
};
const logLevels = {
    a: 0, b: 1, c: 2, d: 3, e: 4, f: 4, g: 5
};

const shouldLog = (level, priority) => {
    const levelPriority = logLevels[level] || -1;
    const logPriority = logLevels[priority];
    return logPriority <= levelPriority;
};

export const LoggerFor = (minLevel = null) => {
    const proxy = new Proxy(console, {
        get: (obj, prop) => {
            let fn = function noop() { };
            let realProp = prop;
            if (prop === 'v' || typeof obj[prop] !== 'function') {
                realProp = 'l';
            }
            const level = minLevel || config.logLevel;
            if (shouldLog((typeof obj[prop] !== 'function' ? 'log' : prop), level)) {
                fn = obj[realProp];
            }
            return (message, ...args) =>
                fn(message, ...args);
        }
    });
    return proxy;
};

```

My webpack configuration is:

```
const slsw = require('serverless-webpack');
const path = require('path');

module.exports = {
    entry: slsw.lib.entries,
    target: 'node',
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: ['babel-loader'],
                include: [
                    path.join(__dirname, 'src')
                ]
            }
        ]
    },
    resolve: {
        modules: [__dirname, 'node_modules']
    }
};

```

and my babel config in package.json is:

```
   "babel": {
        "sourceMaps": "inline",
        "plugins": [
            "transform-runtime"
        ],
        "presets": [
            [
                "env",
                {
                    "targets": {
                        "node": "8.10"
                    }
                }
            ],
            "stage-3"
        ]
    }
```

This has produced the following code fragment 
```
const f = e || r;
return f = 'function' != typeof n[t] ? 'log' : t, o[f] <= (o[f] || -1) && (u = n[c]), (e, ...n) => u(e, ...n);
```

This is obviously not allowed in ES 6 because it's reassigning a value to a `const` . Also to note the code is minified. 
I suspect the issue here is that the minification library used does not work with node 8.10 which (by extension) makes this library not work with node 8.10. 

My question is it possible to either provide an option to disable minification or to find a library that doesn't break when minifying ES 6 code.

Apologies for the wall of code, I tried to keep it as minimal as possible but due to the nature of this issue small variations to the code result in greatly different minified code. 

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.1.1
* ***Webpack version you're using***: 4.5.0
* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: Ubuntu 18.04 LTS

**Comment by geovanisouza92** [comment]
Just for confirmation, have you tried to run webpack directly? I mean, you'll need to replace `slws.lib.entries` with the path to your handler file and call `webpack` (or `node_modules/.bin/webpack`) and see the result.

Is the result valid? If not, maybe it's related to babel or webpack itself...

**Comment by HyperBrain** [comment]
Hi @apokryfos , the plugin _uses_ webpack to transform your code. I assume that you have a configuration issue.

What I saw on the first look is, that you are missing some configuration properties that should be set when using Webpack 4.x in your webpack configuration file:
```
  mode: slsw.lib.webpack.isLocal ? 'development': 'production',
  optimization: {
    // We no not want to minimize our code.
    minimize: false
  },
```
This will configure debug settings properly and generally disable minification.

For other settings and a correct configuration, please have a look at the webpack 4 example: https://github.com/serverless-heaven/serverless-webpack/blob/master/examples/babel-webpack-4/webpack.config.js

**Comment by apokryfos** [comment]
Hello @HyperBrain  and @geovanisouza92  thanks for the response.

```
optimization: {
    // We no not want to minimize our code.
    minimize: false
  }
```

This is exactly what I was looking for. I was unsure where the minification came from, I thought it was coming from this library but as you both mention this is a webpack 4 feature and is not from this library. I suspect it might be an issue with webpack or I'm doing something very wrong.
