### ISSUE TITLE
disable when working with : serverless-offline

### ISSUE THREAD

**Issue by tzookb** [serverless-heaven/serverless-webpack#415]
# Feature Proposal

## Description

For feature proposals:
would like to be able to disable webpack build when working locally with: 
`serverless-offline`

as each build take ~10seconds
and on each save of my code I need to wait :/

**Comment by HyperBrain** [comment]
Hi @tzookb , thanks for the feature request. I agree that this should be available the same way it is already for `serverless invoke local --no-build`.

The workflow would then be:
```bash
serverless webpack
serverless offline --no-build ...
```

The only thing you lose is the continuous build when you change files but that's somehow intended.

**Comment by thejuan** [comment]
Where is this up to? Waiting on the completion of the PR tasks?
