### ISSUE TITLE
Autoredeploy on file change : --watch, but not locally

### ISSUE THREAD

**Issue by eltonio450** [serverless-heaven/serverless-webpack#420]
# This is a  Feature Proposal

## Description

Hello everyone,

I'm not really expert in plugin development, so I post here a feature proposal, but with a good starting point, I will definitively code it and propose a pull request.

We are using AWS Appsync, and it's much easier to test our functions online than locally (because of the "source" cascading mechanism). So, we would really appreciate a way to automatically redeploy single functions on file changes. 

It seems that the --watch option does that with invoke local. I am looking for a way to adapt this mechanism in order to invoke sls deploy -f functionName on a file change.

I am not sure where to plug this kind of mechanism. what could be a good starting point ? Would anyone else be interested in this feature ?

Thank you !

Antoine

**Comment by geovanisouza92** [comment]
Hi @eltonio450, maybe you can use [nodemon](https://www.npmjs.com/package/nodemon) or [warun](https://www.npmjs.com/package/warun) for monitoring, and just running the command `sls deploy -f` in consequence.

**Comment by HyperBrain** [comment]
Hi @eltonio450 , I also see this functionality either completely outside of Serverless or at least in Serverless itself, instead of the plugin. The plugin only forwards Webpack's watch functionality to the Serverless CLI, but should not implement or add that feature for the Serverless framework.
It might be worth to open a feature request in Serverless.

**Comment by eltonio450** [comment]
@geovanisouza92 thanks, but since the command already exists, I was hoping to hook something :)

@HyperBrain ok thank you ! I'll do that ! closing the issue here
