### ISSUE TITLE
Webpack plugin doesn't work with serverless-offline 3.25.5

### ISSUE THREAD

**Issue by arabold** [serverless-heaven/serverless-webpack#421]
# This is a Bug Report

## Description

It might relate to some lifecycle changes made in `serverless-offline` but after updating that plugin from 3.25.4 to 3.25.5 it stops working in combination with `serverless-webpack` 5.1.5. Without `serverless-webpack` everything works as expected.

I've filed it over there, too, as I think a minor version change from .4 to .5 shouldn't contain changes that break compatibility with other plugins, but it might have to be fixed in `serverless-webpack` nonetheless.

https://github.com/dherault/serverless-offline/issues/445

## Additional Data

* ***Serverless-Webpack Version***: 5.1.5
* ***Serverless-Offline Version***: 3.25.5
* ***Webpack version you're using***: 4.15.1
* ***Serverless Framework Version you're using***: 1.28.0

**Comment by HyperBrain** [comment]
Hi @arabold , thanks for the issue 😄 

It seems that the offline issue already has been fixed and the fix is released with `serverless-offline@3.25.6`. Can we close this one then?
