### ISSUE TITLE
Add ability to exclude files from handler lookup

### ISSUE THREAD

**Issue by taschmidt** [serverless-heaven/serverless-webpack#433]
# This is a Feature Proposal

## Description
Please add the ability to exclude certain files from the handler lookup.  This is to get around the extraneous (and possibly error-prone) `WARNING: More than one matching handlers found for 'handler'. Using 'handler.js'` message when there are unit test files in the same directory.

Possible config example:
```
custom:
  webpack:
    excludeFiles: src/**/*.test.[t|j]s
```

Similar or dependent issue(s):
* #405

**Comment by ksnyde** [comment]
Glad to see this issue. Anyone using Typescript is going to immediately run into this. Out of interest, is there currently a work around?

**Comment by designfrontier** [comment]
since it looks like this is just sitting at the moment... I am working on a fix for it. Hope to have a pull request put together in the next few days

**Comment by HyperBrain** [comment]
Released with 5.3.0
