### ISSUE TITLE
Configuration includeModules does not include all dependencies

### ISSUE THREAD

**Issue by danilospa** [serverless-heaven/serverless-webpack#437]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
When using next.js, modules imported on the files of `pages/` directory does not get packed into the Serverless artifacts. This causes the application to break when running on Lambda.

* What did you expect should have happened?
Docs states that when using `includeModules: true`, all dependencies from package.json would be packed with Serverless artifacts. But, for what I have seen on the code, it gets the dependencies based on the chunks output from webpack. Since the files on the `pages/` directory are used only by next.js, they do not appear on the webpack chunks.

* What was the config you used?
`includeModules: true`

## Additional Data

* ***Serverless-Webpack Version you're using***:
5.2.0
* ***Webpack version you're using***:
4.8.3
* ***Serverless Framework Version you're using***:
1.27.3

**Comment by HyperBrain** [comment]
Hi @danilospa , this is the expected behavior. Not _all_ dependencies are installed, but the ones that are actually used (and present in production dependencies).

If you want to package an arbitrary directory or content, you should use the webpack copyfile plugin and configure it in your webpack configuration. Webpack will then include them in your package.

**Comment by danilospa** [comment]
Thanks for the answer, @HyperBrain.

Shouldn't it be the case to make the README more explicit?
```
All modules stated in externals will be excluded from bundled files. If an excluded module is stated as dependencies in package.json, it will be packed into the Serverless artifact under the node_modules directory.
```

From this, it appears that all dependencies from package json would be packed.

**Comment by HyperBrain** [comment]
👍 Good idea. If you don't mind, you can open a PR with the documentation fix, so that it is clear.
