### ISSUE TITLE
Serverless deploy receiving path must be a string or a buffer

### ISSUE THREAD

**Issue by jaldipp** [serverless-heaven/serverless-webpack#443]
I am running the following command and getting an path must be a string or buffer error. 
This works when i don't pass in -p option.  I am trying to separate packaging and deploying for CI/CD.

```bash
node_modules/.bin/serverless deploy -p ./.serverless/

serverless deploy -p ./.serverless
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command logs
Serverless: Load command webpack
Serverless: Invoke deploy
Serverless: Uploading artifacts...

  Type Error ---------------------------------------------

  path must be a string or Buffer

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:636:11)
    at ReadStream.open (fs.js:1996:6)
    at new ReadStream (fs.js:1983:10)
    at Object.fs.createReadStream (fs.js:1931:10)
    at GoogleDeploy.uploadArtifacts (C:\Projects\MMT\mmt-service-resources-12020\node_modules\serverless-google-cloudfunctions\deploy\lib\uploadArtifacts.js:17:18)
From previous event:
    at PluginManager.invoke (C:\Users\jaldip.patel\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (C:\Users\jaldip.patel\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (C:\Users\jaldip.patel\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (C:\Users\jaldip.patel\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\jaldip.patel\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.11.4
     Serverless Version:     1.30.1
```

**Comment by jaldipp** [comment]
service: mmt-service-resources-12020

#pin down serverless framework version
frameworkVersion: "^1.29.2"

#custom variable
custom:
  projectName: nodejs-angular-212118
  webpack:
    webpackConfig: ./config/webpack.config.js   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules

provider:
  name: google
  runtime: nodejs
  project: ${self:custom.projectName}
  region: us-central1
  #memory:
  #timeout: 
  # the path to the credentials file needs to be absolute
  credentials: keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-webpack

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - ./config/webpack.config
    - tests/**
    - README.md
    - .git
    - .gitignore
    - .gcloudignore
    - gulpfile.js
    - keyfile.json
  include:
    - package.json

functions:
  getResourcesFunction:
    handler: getResources
    method: get
    cors: true
    events:
      - http: path

  getResourceByEnterpriseIdFunction:
    handler: getResourceByEnterpriseId
    method: post
    cors: true
    events:
      - http: path

  addResourceFunction:
    handler: addResource
    method: post
    cors: true
    events:
      - http: path




Webpack

const webpack = require('webpack');
const slsw = require('serverless-webpack');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const nodeExternals = require('webpack-node-externals');
const path = require('path');

// You can access the options given to serverles with "slsw.lib.options" and
// the serverless instance with "slsw.lib.serverless". This allows you to dynamically
// build the configuration depending on anything available in serverless (e.g.
// the service definition (slsw.lib.serverless.service.xxxxx)

module.exports = {
    entry: slsw.lib.entries.entry,
    target: 'node',
    mode: slsw.lib.webpack.isLocal ? "development" : "production",
    module: {
      rules: [
        {
          test: /\.json$/,
          exclude: /(node_modules)/,
          use: [
            { loader: 'json-loader' }
          ]
        },
        {
          test: /\.(md|jst|def)$/,
          use: [
            { loader: 'ignore-loader' }
          ]
        },
      ]
    },
    resolve: {
        extensions: ['.js', '.json']
    },
    output: {
        libraryTarget: 'commonjs',
        path: path.join(__dirname, '.webpack'),
        filename: 'index.js'
    },
    externals: [nodeExternals()],
    plugins: [
        new BundleAnalyzerPlugin({
            analyzerMode: 'disabled',
            reportFilename: 'report.html',
            generateStatsFile: false,
            statsFilename: 'stats.json',
            logLevel: 'info',
            openAnalyzer: false
        })
    ]
};

**Comment by HyperBrain** [comment]
Hi @jaldipp ,
it seems that the issue is located in the google provider plugin:
```
at GoogleDeploy.uploadArtifacts (C:\Projects\MMT\mmt-service-resources-12020\node_modules\serverless-google-cloudfunctions\deploy\lib\uploadArtifacts.js:17:18)
```
Can you open an issue there?

**Comment by hassankhan** [comment]
Hi @jaldipp, closing this issue since it seems the issue relates to another plugin. Please let us know if the issue persists and we can re-open it 😉
