### ISSUE TITLE
Configuring package include doesn't work 

### ISSUE THREAD

**Issue by jsi-p** [serverless-heaven/serverless-webpack#445]
Without serverless-webpack plugin this includes the migrations dir in the zip, but with serverless-webpack plugin the migrations dir is missing from the packaged zip:

```
package:
  include:
    - migrations/*.js
```

Serverless version: 1.30.1
Webpack version: 4.17.2
Serverless webpack: 5.2.0
OS: MacOS 10.13.6

**Comment by HyperBrain** [comment]
Hi @jsi-p ,
to include arbitrary folders into your project, you have to use the copy file webpack plugin and configure it properly in your webpack config. Then it should work and webpack will take care to copy the needed directory.

**Comment by jsi-p** [comment]
Thanks @HyperBrain!

**Comment by a-h** [comment]
In case anyone else finds this after coming across the same problem and wondering why your files weren't included...

You'll need to add the plugin to your project.

```
npm i -D copy-webpack-plugin
```

Then add a reference to it in the `webpack.config.js` file:

```javascript
const CopyPlugin = require("copy-webpack-plugin"); 
```

Then, add your required section to the plugins section of the same file.

```javascript
module.exports = {
  ...
  plugins: [
    new CopyPlugin({
      patterns: [{ from: "./.nuxt", to: "./.nuxt" }],
    }),
  ],
}
```
