### ISSUE TITLE
Add support to keep output directory after package/deploy

### ISSUE THREAD

**Issue by aaronjensen** [serverless-heaven/serverless-webpack#453]
# This is a Feature Proposal

## Description

We're trying to upload our sourcemaps to our bug tracker, Sentry. They provide a webpack plugin to do this, but it doesn't play well with multiple webpack configurations (it attempts to upload all source maps for each configuration). Instead of using the plugin, we'd like to use their cli tool. Unfortunately, serverless-webpack cleans up the output path before we have a chance to do this. 

I could write a serverless plugin to slot in before serverless-webpack cleans up probably, but it'd be nice if we could just disable the cleanup step in the configuration.

Thanks!

**Comment by HyperBrain** [comment]
Released with 5.3.0
