### ISSUE TITLE
Successful serverless offline lambda function behaves differently when deployed using serverless-webpack

### ISSUE THREAD

**Issue by lokimckay** [serverless-heaven/serverless-webpack#455]
# This is a Bug Report

## Description

Full disclosure: I have already raised a ticket in another related repository [here](https://github.com/apollographql/apollo-server/issues/1828). I raised this ticket because I am not sure if the issue I am having is related to serverless-webpack or apollo-datasource-rest. Any guidance is much appreciated :)

To reproduce please follow readme in [this repo](https://github.com/sneyed/apollo-datasource-rest-issue)

For bug reports:
* What went wrong?
I get the following error once I have deployed to Lambda, but there is no issue when using serverless offline.
`TypeError: Right-hand side of 'instanceof' is not an object`
* What did you expect should have happened?
I should be able to call the deployed Lambda endpoint and receive a successful response with no errors
* What was the config you used?
See repro repo https://github.com/sneyed/apollo-datasource-rest-issue
* What stacktrace or error message from your provider did you see?
See https://github.com/sneyed/apollo-datasource-rest-issue/blob/master/FULLERROR.json

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):
* [#1828](https://github.com/apollographql/apollo-server/issues/1828)

## Additional Data

* ***Serverless-Webpack Version you're using***: ^5.2.0
* ***Webpack version you're using***: ^4.20.2
* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Windows 8.1
* ***Stack Trace (if available)***: [https://github.com/sneyed/apollo-datasource-rest-issue/blob/master/FULLERROR.json](https://github.com/sneyed/apollo-datasource-rest-issue/blob/master/FULLERROR.json)

**Comment by hassankhan** [comment]
Hi @sneyed, it does indeed look like the issue is with `apollo-datasource-rest`, can you confirm?

**Comment by lokimckay** [comment]
Yes related to `apollo-datasource-rest`
