### ISSUE TITLE
Memory usage keeps increases on every request

### ISSUE THREAD

**Issue by jaydp17** [serverless-heaven/serverless-webpack#473]
# This is a Bug Report

## Description

Possible memory leak. The memory usage of the process keeps increasing on every request.

I've created a [minimal repo](https://github.com/jaydp17/serverless-memory-leak/tree/webpack) (with hello world example) using [serverless-offline](https://github.com/dherault/serverless-offline) & serverless-webpack to demonstrate the issue.

Initially, I thought that it was a memory leak in serverless-offline, as mentioned in https://github.com/dherault/serverless-offline/issues/539, but after investigating a little bit I suspect that it's because of serverless-webpack.

Also, I tried figuring out where is the memory leak using heapdumps, but maybe I'm not so good at identifying leaks.
Anyways, please do let me know, in case you need any help.

For bug reports:
* What went wrong?
On every subsequent request the memory usage increases.

* What did you expect should have happened?
For the memory usage to roughly stay constant.

* What was the config you used?
Example [repo](https://github.com/jaydp17/serverless-memory-leak/tree/webpack), please make sure you check the `webpack` branch.

* What stacktrace or error message from your provider did you see?
N/A

Similar or dependent issue(s):
* https://github.com/dherault/serverless-offline/issues/539

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.2.0
* ***Webpack version you're using***: 4.28.1
* ***Serverless Framework Version you're using***: 1.35.1
* ***Operating System***: macOS
* ***Stack Trace (if available)***:

**Comment by jaydp17** [comment]
In my case, it **wasn't** actually serverless-webpack that was creating the leak, it was because of [serverless-offline](https://github.com/dherault/serverless-offline) trying to reload the handler without working around this bug (https://github.com/nodejs/node/issues/8443).

The issue has been fixed in `v3.33.0` of serverless-offline.

**Comment by vicary** [comment]
@AXSJ When using `serverless-webpack`, you don't need `serverless-bundle`, `serverless-plugin-typescript`, `serverless-jetpack` or `serverless-esbuild`. Using more than one of these at the same time may lead to undefined behavior.

If you are still having problems, please open a new issue instead.
