### ISSUE TITLE
Default color output should depend on TTY

### ISSUE THREAD

**Issue by c0d3d** [serverless-heaven/serverless-webpack#480]
# This is a Feature Proposal

## Description

When piping the default webpack output into a file (or when using CI/CD tool without shell color escape support), color escapes are added. The plugin should first check if the output is a tty before writing colors (this is a more sensible default IMO). It can still be overridden explicitly, but by default the plugin should decide if the output supports colors before writing them.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.2.0
* ***Webpack version you're using***: 4.16.4
* ***Serverless Framework Version you're using***: 1.30.0
* ***Operating System***: OSX

**Comment by c0d3d** [comment]
@HyperBrain, can you take a look at this?

**Comment by HyperBrain** [comment]
@c0d3d I will check

**Comment by HyperBrain** [comment]
Released with 5.3.0
