### ISSUE TITLE
exclude /opt/ from build process to take advantage of layers

### ISSUE THREAD

**Issue by andresmijares** [serverless-heaven/serverless-webpack#487]
# This is a (Bug Report / Feature Proposal)
Bug Report
## Description
When trying to use custom files from AWS layers, I cannot exclude `/^\/opt/` from the build process.
For bug reports:
* What went wrong?
I tried to exclude the `/^\/opt`, however, it still tries to render it.
* What did you expect should have happened?
The build process should be completed with 0 status.
* What was the config you used?
```
webpack
    includeModules:
      forceExclude:
        - /^\/opt/
```
* What stacktrace or error message from your provider did you see?
```
ERROR in ./handler.js
Module not found: Error: Can't resolve '/opt/somefolder/libs/commons' in '/somepath/'
 @ ./handler.js 7:38-76
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
I'm trying to use AWS layers references from another project.
* If there is additional config how would it look

Similar or dependent issue(s):

## Additional Data

* ***Serverless-Webpack Version you're using***: ^5.2.0
* ***Webpack version you're using***:
* ***Serverless Framework Version you're using***: latest
* ***Operating System***:
* ***Stack Trace (if available)***:

**Comment by dashmug** [comment]
Why is this closed? How did you fix it?

**Comment by GektorGrom** [comment]
@andresmijares Did you ever figure out how to forceExclude layers?

**Comment by rplute** [comment]
@andresmijares, were you able to resolve this?

**Comment by MarcWadai** [comment]
+1, any solution ?

**Comment by andresmijares** [comment]
Hi, not, I gave out with this approach, I was not able to solve it, however, I haven't tried again since, I closed the issue cause it didn't get any attention. Probably it is a good time to re-open it if someone wants to take care of it, Best.

**Comment by MarcWadai** [comment]
Thanks for your answer.. what was your approach ? Did you still use webpack ? 
For my side I had to use webpack in order to copy some conf files into each lambdas..

**Comment by andresmijares** [comment]
I was not using webpack at the time, I think the problem on my use case is that I needed to isolate dependencies per layer, however, webpack was forcing me to keep em on multiple bundles, I was trying to run away for it... I did end up not using layers and moved on with my life, not sure how this evolved it, it has been a year now.

**Comment by alexbondify** [comment]
module.exports = {
  //...
  externals: [nodeExternals(), /^\/opt/, 'aws-sdk',, // exclude Lambda Layers
  //...
};
