### ISSUE TITLE
Empty lines while stats: 'errors-only'

### ISSUE THREAD

**Issue by Enase** [serverless-heaven/serverless-webpack#499]
# This is a Improvement

## Precondition
Setup webpack config with `stats: 'errors-only'`

## Description
As a result you wanna see silent output while compile process, but right now any compiled item produce empty line as a result, due to `this.serverless.cli.consoleLog` behavior.

## Additional Data
Screen while `sls deploy`
![Screen Shot 2019-05-10 at 17 41 34](https://user-images.githubusercontent.com/2459495/57535426-dfbd2580-734a-11e9-8355-dad4056ed552.png)

**Comment by HyperBrain** [comment]
Released with 5.3.1
