### ISSUE TITLE
Upgrade ts-node package to more recent version

### ISSUE THREAD

**Issue by P-K** [serverless-heaven/serverless-webpack#521]
# This is a Feature Proposal

## Description

Github security alerts is letting us know that our version of diff is not up-to-date (currently sitting at v3.1.0). This is because v5.3.1 of `serverless-webpack` uses `ts-node` v3.30, which then uses `diff` v3.1.0. 

For feature proposals:
* Upgrade the version of `ts-node` being used so that the version of `diff` is at least v.3.5.0

## Additional Data

* ***Serverless-Webpack Version you're using***: v 5.3.1

**Comment by HyperBrain** [comment]
Good catch 👍 Do you know any caveats when upgrading, or should it not break anything?
