### ISSUE TITLE
Question: separate webpack configs for each function

### ISSUE THREAD

**Issue by Pavel910** [serverless-heaven/serverless-webpack#525]
# This is a Question
Is it possible to specify a `webpack.config.js` for individual functions? 

I am packaging functions individually and would like to bundle some functions with entirely different config from other functions. An alternative solution I was thinking about is writing a node script that runs webpack for each individual function, and once done runs `sls offline start` using `nodemon` to watch for changes (I think this way I wouldn't need the `serverless-webpack` plugin).

Any ideas or suggestions are very welcome! Thank you!

P.S. if there is no such feature and you think it might be beneficial for the project, I would be interested in contributing the feature myself ❤️

**Comment by HyperBrain** [comment]
Hi @Pavel910 , thanks for asking 👍 
Can you tell, what exactly is the reason why you need completely different webpack configurations for different functions? I'm just curious because for us (at my company) it was never something that came up.

**Comment by Pavel910** [comment]
@HyperBrain we have a monorepo project containing many API functions, but also have this one SSR lambda which is configured for server-side-render bundle of our SPA, which is totally different than the API functions. Just that. I would still love to use `sls deploy` to deploy all of the functions at the same time, hence the idea.

If you have an idea for a different approach, I would greatly appreciate it. Thank you!

**Comment by tysonclugg** [comment]
None of the examples in the [Webpack configuration file](https://github.com/serverless-heaven/serverless-webpack/blob/master/README.md#webpack-configuration-file) section of the README detail how to apply config for a monorepo containing many API functions - the `entry` config always refers to a single input file.

The async config callback example in the README is similarly limited, as the callback doesn't take any args (such as a `functionObject`) that would allow separate configs for each function.

I'm new to Serverless, am I correct in assuming that support for multiple functions is a somewhat recent addition and hence not well supported yet?

**Comment by Pavel910** [comment]
@tysonclugg this problem is very elegantly solved with the release of `serverless components`. You can have a separate webpack config for each of your functions, I tried it - it works great.

Take a look at https://github.com/serverless/components

**Comment by Pavel910** [comment]
NOTE: closing since this issue is not solvable by `servelress-webpack` but there are other ways to achieve separate configs (see comment above).

**Comment by tysonclugg** [comment]
> @tysonclugg this problem is very elegantly solved with the release of `serverless components`. You can have a separate webpack config for each of your functions, I tried it - it works great.
> 
> Take a look at https://github.com/serverless/components

It don't think it will work for me, because support for `cloudflare-workers` [was added on 25 July 2018](https://github.com/serverless/components/pull/232) but then [was removed on 26 March 2019](https://github.com/serverless/components/pull/398).

I was unable to find where the `cloudflare-workers` component now lives...  :slightly_frowning_face:

**Comment by tysonclugg** [comment]
@Pavel910 can you please confirm if https://github.com/serverless/components/issues/395 has been resolved?  It remains open, and implies that using webpack with https://github.com/serverless/components won't work.

**Comment by Pavel910** [comment]
@tysonclugg you don't need plugins at all to make use of webpack. Take a look at how [@serverless/website](https://github.com/serverless-components/website/) works, you will find a `hook` input, which allows you to run any npm script yourself, thus allowing you to run webpack build before deploy.

For functions you need [@serverless/function](https://github.com/serverless-components/function), which at this point does not support `inputs.hook`, but it is very easy to create your own component and add support for that input, here is the complete code for your custom component:

```js
const path = require("path");
const execa = require("execa");
const { Component } = require("@serverless/core");

class ServerlessFunction extends Component {
    async default(inputs = {}) {
        const functionRoot = path.join(this.context.instance.root, inputs.root);
        
        if (inputs.hook) {
            this.context.log("Building function");
            const [cmd, ...args] = inputs.hook.split(" ");
            await execa(cmd, args, {
                cwd: functionRoot,
                env: { NODE_ENV: "production" },
                stdio: "inherit"
            });
        }

        const lambda = await this.load("@serverless/function");
        return await lambda(inputs);
    }
}

module.exports = ServerlessFunction;
```

What this does: it checks if your `inputs` have a `hook` parameter specified, and if yes - runs the script using `execa`, Then it simply runs `@serverless/function` component to deploy the function - that's it.

**Comment by cristiam86** [comment]
Awesome response @Pavel910, but since I'm very new on webpack, can you please clarify more on how to build the function?  I'm using the [Backend Microservices Template](https://github.com/serverless/components/blob/master/templates/backend-microservices/serverless.yml) and my idea is to add a custom function component that does the same as the [https://github.com/serverless-components/function](@serverless/function) component but adding your hook part.

I was digging into this plugin to see if I find a way to do the same with webpack but I'm very lost.

1. Do I need a webpack config? 
2. What would be the hook command?
3. How does the serverless component that it should upload the built function instead of the raw one?

Thanks again!
