### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by clar-cmp** [serverless-heaven/serverless-webpack#545]
A release hasn't been done since June, but TypeScript type definitons have been added. since then. Could you do another release to include these?

Thanks!

**Comment by miguel-a-calles-mba** [comment]
May you please submit a PR with the desired change or further describe the changes you are requesting?

**Comment by clar-cmp** [comment]
I'm specifically talking about a commit that's already on master but hasn't been released to NPM. Or at least, wasn't at the time of writing.

**Comment by miguel-a-calles-mba** [comment]
We are preparing a new release. That commit should get rolled in.

**Comment by miguel-a-calles-mba** [comment]
We draft release 5.3.2 https://github.com/serverless-heaven/serverless-webpack/releases/tag/untagged-54bd590e1d9f15338a68. We plan to get this out soon. Closing this issue.
