### ISSUE TITLE
support layer-provided lambda handlers (e.g. new relic lambda layer)

### ISSUE THREAD

**Issue by thekelvinliu** [serverless-heaven/serverless-webpack#548]
# This is a Feature Proposal

## Description

i'm using this plugin to keep my lambda deployments small and fast -- it's fantastic, and i really appreciate the effort put into this project 😄 i'd like to instrument my nodejs lambda with newrelic, using their published lambda layer. i am using their [manual steps documentation](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-new-relic-monitoring-aws-lambda#manual-layer). this requires changing the handlers in serverless config to `newrelic-lambda-wrapper.handler` and setting `NEW_RELIC_LAMBDA_HANDLER` to the original handler path. this breaks serverless-webpack validation:

```
No matching handler found for 'newrelic-lambda-wrapper' in '/path/to/repo'. Check your service definition.
```

in order to support this type of setup, this plugin would need more flexibility with the handlers. instead of only looking at the function config, maybe there could be other ways of setting the handler path? for example in my case, i'd want to configure it to use `NEW_RELIC_LAMBDA_HANDLER` environment variable set on the function config.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.1
* ***Webpack version you're using***: 4.41.5
* ***Serverless Framework Version you're using***: 1.60.5
* ***Operating System***: macOS 10.14.6
* ***Stack Trace (if available)***:

**Comment by proddimus** [comment]
This has caused quite a bit of frustration, great to get this fixed.

**Comment by kirrg001** [comment]
+1

Running into this issue because the handler is inside the lambda layer. This is working great with `serverless` and `serverless-offline`, but not with `serverless-webpack`.

Do you a accept a PR to skip this validation step?
