### ISSUE TITLE
QUESTION: build once run anywhere possible with serverless-webpack?

### ISSUE THREAD

**Issue by ed4becky** [serverless-heaven/serverless-webpack#558]
We currently have 5 environments we deploy our lambda functions to (dev, test, uat, stage, prod)

in our CI/CD pipeline we call sls deploy for each one, triggering a webpack build each time.

Is it possible with serverless-webpack to build the functions once, and deploy the single build to each environment? I know some configuration files get built with stage specific names (roles, the arn for each function, others...), but is that a separate part of the process from the webpack build? Or doe the webpack step include stage specific output?

Can I run the package thru webpack once, and include the results in the packaging for each stage?

**Comment by sakthi-ganesh** [comment]
Any update on this? Currently "serverless deploy" command is triggering a compile, but i would need to refer the already compiled code in "output" folder during deployment. Please suggest

**Comment by miguel-a-calles-mba** [comment]
This PR might be what you are seeking.

https://github.com/serverless-heaven/serverless-webpack/pull/560

You can install the PR for now; that what I am doing.

**Comment by miguel-a-calles-mba** [comment]
Here's how I do it.

1. Run `sls webpack`
2. Zip (or tgz) the `.serverless` directory and include it as part of my artifacts.
3. Extract the zip package right before deploy time.
4. Deploy `sls deploy --no-build` to reuse the extracted `.serverless` directory.

**Comment by sakthi-ganesh** [comment]
Thanks Miguel!

But sill the --no-build is doing the build before deploy. I configured my package.json with the below 2 scripts

"build": "serverless webpack",
"deploy": "serverless deploy --no-build"

Please let me know if i am missing any item here

**Comment by miguel-a-calles-mba** [comment]
Try `npm i github:serverless-heaven/serverless-webpack#pull/560/head` to install the PR.

**Comment by miguel-a-calles-mba** [comment]
This PR is tentatively planned for release 5.3.3

**Comment by sakthi-ganesh** [comment]
Thanks Miguel!. It works great and as expected.. Please release 5.3.3 at the earliest.. Eagerly waiting to see it in npm repository.

**Comment by miguel-a-calles-mba** [comment]
I'm eagerly waiting for this PR too! We need to release 5.3.2 first. =)

**Comment by sakthi-ganesh** [comment]
Hi Miguel,

Could you please tell me if any release dates planned for 5.3.2 and 5.3.3?

**Comment by miguel-a-calles-mba** [comment]
Hi @sakthi-ganesh , 5.3.2 should go out soon. Just waiting for approval of the release PR.

https://github.com/serverless-heaven/serverless-webpack/pull/582
