### ISSUE TITLE
Massive Performance Degradation on zipping when upgrading from Node 8

### ISSUE THREAD

**Issue by liron-strattic** [serverless-heaven/serverless-webpack#561]
# This is a Bug Report
## Description
- What Went Wrong?
We just upgraded our functions from node 8 and when we did, our build performance took a drastic hit. On node 8 it takes about 2-3 seconds per function for zipping the function. After upgrading (we tried both node 10.19.0 and node 13.10.0) the performance dropped to about 20 seconds per function during the zip.
- What did you expect should have happened?
Performance should have stayed the same
- What was the config you used?
node --max-old-space-size=40960 /usr/local/bin/sls deploy --verbose
- What stacktrace or error message from your provider did you see?

On Node 8:
 Serverless: Zip function: /builds/...../.webpack/FunctionOne [3271 ms]
 Serverless: Zip function: /builds/...../.webpack/FunctionTwo [1922 ms]
 Serverless: Zip function: /builds/...../.webpack/FunctionThree [5756 ms]
 Serverless: Zip function: /builds/...../.webpack/FunctionFour [1823 ms]

On Node 10:
 Serverless: Zip function: /builds/...../.webpack/FunctionOne [19663 ms]
 Serverless: Zip function: /builds/...../.webpack/FunctionTwo [19252 ms]
 Serverless: Zip function: /builds/...../.webpack/FunctionThree [19305 ms]
 Serverless: Zip function: /builds/...../.webpack/FunctionFour [18654 ms]

## Additional Data

* ***Serverless-Webpack Version you're using***:
Tried this with serverless-webpack, both using version 5.3.1 which includes archiver 2.1.1 ("https://registry.yarnpkg.com/serverless-webpack/-/serverless-webpack-5.3.1.tgz#39c3d0b23f92273702ac418fd33fa7029e085176")
Also tried with the latest serverless-webpack version in git (https://github.com/serverless-heaven/serverless-webpack#71c86c30450e8bd677cbccb2ada81a00c6a1c7d8), which includes archiver 3.0.3.

* ***Webpack version you're using***:
4.26.0

* ***Serverless Framework Version you're using***:
1.33.2

* ***Operating System***:
Docker [debian (jessie) based]
FROM node:8.10.0
FROM node:10.19.0
FROM node:13.10.0

* ***Stack Trace (if available)***:

**Comment by liron-strattic** [comment]
We just upgraded serverless to be the latest version 1.66, and we see the same issue there.

Framework Core: 1.66.0
Plugin: 3.4.1
SDK: 2.3.0
Components: 2.22.3

**Comment by shierro** [comment]
wow, this issue make me want to try node 8 to improve my project's build size! 😂

**Comment by amitaymolko** [comment]
Yeah, we had a similar experience.  
Would be nice to reduce the build times, its hard when a deployment takes 25min...
