### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by clar-cmp** [serverless-heaven/serverless-webpack#563]
This package does not seem to be maintained. Is there any well-adopted fork that could be suggested instead, and/or does the serverless-heaven org have any plans to actually maintain this?

**Comment by rdsedmundo** [comment]
Copied from #517 

```
Guys, only @HyperBrain have write access to the repo, the other members of the organization cannot merge the PR.

As you can tell by looking at his Github activity in the last 2 years (starting at 2018 H2 and forward) this repository isn't actively maintained anymore. I'd recommend someone making a fork where we can accept this fix and others potentially from the other open PRs.

I'm personally a user of this project and a heavy webpack user, but had to drop it due to some of its limitations, including the one that this PR is intending to fix. I'd be happy to lead the creation of a fork and setting up a maintainer team.
```

> I'd be happy to lead the creation of a fork and setting up a maintainer team.

Any thoughts?

**Comment by franciscocpg** [comment]
Hi guys.

I've emailed @HyperBrain asking him to take a look at this issue. Maybe we could wait a few days before creating a new fork?

**Comment by rdsedmundo** [comment]
This has happened in the past, he appeared, merged a few PRs, and was gone again. [Actually, it was on an issue that I had created, but in another repository, serverless-aws-alias](https://github.com/serverless-heaven/serverless-aws-alias/issues/154). I'm by no means saying this with a bad mood, I understand that he probably has a full-time job and other things to do, and working in your spare time in open-source projects for free isn't something you can (or is willing to) do all the time.

I myself also have a full-time job and would need the help of a few other folks in order to get the project going. My idea is to focus on those critical fixes like the serial building, merging them and getting released, and then we can think on a maintenance plan for new features and etc for the long-term.

**Comment by mogusbi-motech** [comment]
Would it not be better for him to maybe hand over this repo to someone or a couple of trusted people? (provided we can get a hold of him)

Forking would mean needing to publish a brand new package on NPM and you'd have the task of directing anyone who lands on here to go and install the newer, more up to date version instead

**Comment by rdsedmundo** [comment]
> (provided we can get a hold of him)
That will be the question. Let's wait until the end of this week to see if he shows up, otherwise, we make a decision by Monday.

I agree that maintaining the current repo + NPM package is way easier than spinning up new ones.

**Comment by coyoteecd** [comment]
Doesn't even have to be "handing over the repo", just add a few contributors with write access that can merge PRs and publish new releases.

**Comment by rdsedmundo** [comment]
It's been 1 week. Shall we make the fork? 😄

**Comment by tusamcalles** [comment]
Please do. I'd like to use https://github.com/serverless-heaven/serverless-webpack/pull/560.

**Comment by tusamcalles** [comment]
I messaged @HyperBrain on LinkedIn and asked if he could add additional maintainers. It would be great to update this plugin. Hope he has time.

**Comment by franciscocpg** [comment]
@tusamcalles
I've emailed him about a week but no response.

Do you have luck?

**Comment by tusamcalles** [comment]
He just replied. Yay!

I'm sending him a list of maintainers.

**Comment by miguel-a-calles-mba** [comment]
FYI:

```
Hi Miguel,

I'm just adding the people.

Please check https://github.com/orgs/serverless-heaven/teams/serverless-webpack-team/discussions that we used to communicate and discuss.
From my side you are good to go. Please remember to follow strict SEMVER, i.e. breaking changes must increase major, feature additions minor, and bugs
not changing the behavior can be patch version increases.

As soon as there is a new version ready, I can validate and push NPM.

Cheers,
Frank
```

**Comment by miguel-a-calles-mba** [comment]
@rdsedmundo Should we close this issue now? I believe you are now a maintainer.

**Comment by clar-cmp** [comment]
I'll close because it seems like you've gotten it under control. :smile:

**Comment by clar-cmp** [comment]
Also going to mention that you can close #545 once the new version is pushed to NPM as well
