### ISSUE TITLE
Question: Reusing webpack zip files

### ISSUE THREAD

**Issue by tusamcalles** [serverless-heaven/serverless-webpack#564]
# This is a Question

## Description

Is there a way to reuse the `.webpack` folder? I would like to build the `.webpack` and re-use, such that the sls package process does not rebuild the individual function zip files.

## Additional Data

* ***Serverless-Webpack Version you're using***:
serverless-webpack: 5.3.0
* ***Webpack version you're using***:
webpack: 4.32.2
webpack-node-externals: 1.7.2
* ***Serverless Framework Version you're using***:
serverless: 1.60.5
* ***Operating System***:
darwin
* ***Stack Trace (if available)***:
N/A

**Comment by jamesmbourne** [comment]
@tusamcalles this sounds like #398 - there is a PR open https://github.com/serverless-heaven/serverless-webpack/pull/560 which should implement support for using the `--no-build` flag when you run `serverless-deploy` which will re-use the existing output generated by `serverless webpack`.

Feel free to try it out and let me know how it works for you.

I am currently using this feature across a number of services in production.

**Comment by tusamcalles** [comment]
This is exactly what I was looking for. It works great!
