### ISSUE TITLE
No hot reloading after code changes

### ISSUE THREAD

**Issue by cyberwombat** [serverless-heaven/serverless-webpack#588]
# This is a Bug Report 

## Description

For bug reports:
* What went wrong?
When making code changes when running serverless-offline I have to kill and restart to see the changes. I do see the console printing out notifications that it saw the changes and it' reloading and the code in .webpack dir is updated but the actual running code stays the same.
I have this issue both when running Jest test as well as when calling the code from my client app offline.

* What did you expect should have happened?
Hot reload new code
* What was the config you used?
webpack.config.js
```

const path = require('path')
const nodeExternals = require('webpack-node-externals')
const slsw = require('serverless-webpack')

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  target: 'node',
  externals: [nodeExternals()],
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js'
  },
  resolve: {
    modules: [__dirname, path.resolve(__dirname, 'src'), 'node_modules']
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'babel-loader'
          }
        ]
      }
    ]
  }
}
```
Order of plugins:
```
 - serverless-dotenv-plugin
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-offline
```
Config:
```
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false 
    packager: "yarn"
```
.babelrc
```

{
  "plugins": [
    [
      "module-resolver",
      {
        "root": [
          "./src"
        ]
      }
    ]
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ]
}
```

## Additional Data
* ***Command***:
IS_OFFLINE=true serverless offline start -a api -s dev"
* ***Serverless-Webpack Version you're using***:
5.3.2
* ***Webpack version you're using***:
4.42.1
* ***Serverless Framework Version you're using***:
1.67.1
* ***Serverless Offline Version you're using***:
6.1.4
* ***Operating System***:
MacOS 10.15.4

I've tried a variety of config with no success.  I wonder if it's something w babel/webpack running differently - for example I use module root resolving to get rid of `../../` path fragments and Ive noticed that I have to set them both in webpack and babel. If I put in webpack only, serverless loads without issue but when I run my test (jest) it fails finding module. Adding babelrc resolver address that.

Any idea what is happening?  Posted on SO but I think this is too sls specific.

**Comment by eurobob** [comment]
See #566

**Comment by cyberwombat** [comment]
Ok. Thanks - Ill watch the other thread to see if it gets fixed.

**Comment by JesusDR01** [comment]
Check this comment https://github.com/dherault/serverless-offline/issues/864#issuecomment-1192948286

**Comment by ps2-controller** [comment]
While this does technically work for me using `sls offline start --reloadHandler`, it takes up to several minutes to run the latest code, and there's no CLI feedback, so I don't know when the new code is running. So in practice, I have to kill the development server and restart it on every code change. 

Here's [a repo I created](https://github.com/ps2-controller/serverless-offline-issue) to minimally reproduce the issue.
