### ISSUE TITLE
serverless-webpack has unmet peer dependency

### ISSUE THREAD

**Issue by ZebraFlesh** [serverless-heaven/serverless-webpack#633]
# This is a Bug Report

## Description
After doing an `npm install --save-dev serverless-webpack` I received a warning about unmet peer dependencies from npm:
```
npm WARN ts-node@8.10.2 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
```
My project doesn't use typescript, so this was unexpected. It seems like `ts-node` should be an [optionalDependency](https://docs.npmjs.com/files/package.json#optionaldependencies) instead of a dependency.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.4
* ***Webpack version you're using***: 4.44.1
* ***Serverless Framework Version you're using***: 1.80.0
* ***Operating System***: macOS 10.15.6 (Catalina)
* ***Stack Trace (if available)***: N/A

**Comment by j0k3r** [comment]
I agree with you. But as I don't use TypeScript either I don't know how to properly fix it.

Does people using TypeScript always have the `ts-node` deps? How can we force them to install it? Because the deps is optional for people not using TypeScript but it's required if they use it.

How can we solve that?

Related PR https://github.com/serverless-heaven/serverless-webpack/pull/129

**Comment by ZebraFlesh** [comment]
Based on [the instructions from webpack](https://v4.webpack.js.org/configuration/configuration-languages/#typescript), I'm pretty sure that people using TypeScript for their webpack file will have `ts-node` installed. That's why optional dependencies seems like the right answer. Looking at the [docs for `optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) npm notes:
> It is still your program’s responsibility to handle the lack of the dependency.

So perhaps `serverless-webpack` would need to provide a meaningful error message if the `require('ts-node')` call failed.

**Comment by j0k3r** [comment]
Thanks for all these information!

**Comment by j0k3r** [comment]
With 5.3.5 I now have:

```
warning "serverless-webpack > ts-node@9.0.0" has unmet peer dependency "typescript@>=2.7".
```

😕 
But there is nothing we can do now 🤷
