### ISSUE TITLE
External modules are not packaged with webpack 5

### ISSUE THREAD

**Issue by janicduplessis** [serverless-heaven/serverless-webpack#651]
# This is a Bug Report

## Description

Since updating to the release version of webpack 5, it seems like external modules are no longer packaged. I investigated a bit and in `packExternalModules#getExternalModules` I don't see the externals I specify in my webpack config. I checked webpack 5 release notes but could not find a not about that and how to fix it. As a workaround I was able to use `stats.compilation.modules` instead of `chunks` and it does include the externals. Not sure if this is a proper fix though.

Similar or dependent issue(s):
N/A

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.5
* ***Webpack version you're using***: 5.1.3
* ***Serverless Framework Version you're using***: 2.8.0
* ***Operating System***: MacOS 10.15.7
* ***Stack Trace (if available)***: N/A

**Comment by aecorredor** [comment]
Facing the same issue here. Downgrading webpack to 4.44.2 solves the issue for us. We were trying to upgrate to the above mentioned versions when we faced the issue. We also use `serverless-plugin-monorepo`.

**Comment by j0k3r** [comment]
I got the issue too.
I was sure the package was OK with webpack 5 after https://github.com/serverless-heaven/serverless-webpack/pull/472

**Comment by lmanerich** [comment]
I got this issue too and found that all modules load with:

```javascript
const myModule = require('myModule')
```

It works, but loading with

```javascript
import MyModule from 'myModule';
```

Does not.

**Comment by sahasayan** [comment]
Facing the same issue, had to downgrade to `webpack@4.44.2`.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.5
* ***Webpack version you're using***: 5.3.0
* ***Serverless Framework Version you're using***: 2.8.0
* ***Operating System***: Ubuntu 20.04 LTS
* ***Stack Trace (if available)***: N/A

**Comment by maxholman** [comment]
I was able to work around this by disabling `optimization.concatenateModules`  (defaults to true in production mode)

**Comment by crespowang** [comment]
> I was able to work around this by disabling `optimization.concatenateModules` (defaults to true in production mode)

Thanks for sharing the workaround. I am wondering what's the reason behind it, and if it is the right solution or there is a better way of fixing the problem.

**Comment by alexandrusavin** [comment]
@crespowang I guess this might have something to do with the issue:
![image](https://user-images.githubusercontent.com/1612455/100883184-57641f80-34b0-11eb-9329-ec301ccbd43d.png)

used here:

https://github.com/serverless-heaven/serverless-webpack/blob/38135e4443c7d7e8506010f0c3e411220abe6f24/lib/packExternalModules.js#L193-L214

**Comment by joshuanapoli** [comment]
I found that webpack@5.0.0-beta30 packages node modules correctly. Beginning with webpack@5.0.0-beta31, node modules are not packaged.

**Comment by derricktang94** [comment]
After added the concatenateModules: false option, there is another deprecation warning which is **Module.issuer: Use new ModuleGraph API**

**Comment by TechTeam12** [comment]
Using serverless-webpack 5.3.5, and webpack 5.21.2 this looks like it is still an issue.

**Comment by clar-cmp** [comment]
Also experiencing these issues, and the above workaround also does work. Might be worth pinning this issue so others know about the workaround until it's fixed.

**Comment by rstrand** [comment]
I had an issue where the workaround compiled but source maps were broken. Rolling back to webpack 4 was the only fix I could get to reliably work.

**Comment by Enase** [comment]
@j0k3r Is there any chance to fix webpack 5 related issues?

**Comment by janicduplessis** [comment]
Opened a PR with the fix I've been using for a while. If anyone would like to help test it that'd be awesome, esp webpack4 backwards compat.

https://github.com/serverless-heaven/serverless-webpack/pull/746

**Comment by j0k3r** [comment]
Thanks @janicduplessis, I'll try on my webpack4 projects next week.

**Comment by lmanerich** [comment]
One thing to note, using webpack5 and this workaround, result in a much larger app size

```
optimization: {
        // fix node modules not packaged into zip
        concatenateModules: false
    },
```

**Comment by janicduplessis** [comment]
The workaround will not be needed anymore in the upcoming 5.4.1 release! So make sure not to forget to remove it :)

**Comment by j0k3r** [comment]
5.4.1 was released yesterday: https://github.com/serverless-heaven/serverless-webpack/releases/tag/v5.4.1

**Comment by manelio** [comment]
Same problem, but neither the `concatenateModules: false` workaround nor the Webpack version (5.53.0) seems to work.

The code is working when compiled with Webpack 4. I reduced the code at its minimum:

```
import { Test1 } from './Test1';
const { Test2 } = require('./Test2');

console.log(Test1, Test2);
// Here Test1 and Test2 are defined

const component = () => {
  return () => {
    console.log(Test1, Test2);
    // Here Test1 is undefined, but Test2 is defined
  }
};

define([], component);
```

`Test1.js` and `Test2.js` are one line files:

```
export const Test1 = 1
```

```
export const Test2 = 2
```

Maybe the problem here comes from the weird use of `requirejs (realize the last `define`) for loading my bundled code. But as I said, this has been working for months with Webpack v4.

Anyone has any clue?

**Comment by Javarome** [comment]
Same problem when using webpack 5.70.0 + webpack-dev-server 4.7.4 + `concatenateModules: false`. Did you find a solution/workaround @manelio ?

**Comment by vithalreddy** [comment]
anyone found solution or workaround for this?

**Comment by bazyliszek10000** [comment]
Same problem when using webpack 5.75.0.

**Comment by vicary** [comment]
For anyone who still has this issue, please open up a new issue with a minimum reproduction repo so we can quickly nail down the cause. Thanks a lot.
