### ISSUE TITLE
Question: does this support Serverless framework v2? 

### ISSUE THREAD

**Issue by damonmaria** [serverless-heaven/serverless-webpack#652]
The very first line of the README states: "A Serverless v1.x plugin..."

I've upgraded to Serverless v2 and things seem to work. 

I'm just checking, does the README need to be updated or is there an issue? Couldn't find anything in the issues list but it's hard set of keywords to search for.

**Comment by j0k3r** [comment]
Thanks for your feedback 👍
I haven't test it myself on Serverless v2.
Maybe we'll see if we have other feedback if it works or not and then update the readme.

**Comment by astuyve** [comment]
Hey @damonmaria - we just dropped support for node 6 and 8 in Serverless Framework v2, so my hunch is that serverless-webpack should still work.

**Comment by coyoteecd** [comment]
I am using a fork of serverless-webpack from 5.3.5; we have upgraded to Serverless Framework v2 and did not encounter any issues caused by serverless-webpack.

**Comment by cdelgado-fexp** [comment]
I came here with the same doubt... maybe it would be worth updating the README?

**Comment by moroine** [comment]
I've been using it on serverless2 for 6months+ without any issues

**Comment by j0k3r** [comment]
Still we need to update test to work properly on v2 https://github.com/serverless-heaven/serverless-webpack/pull/733

**Comment by coyoteecd** [comment]
@j0k3r it might be that v2.30 does not work with this plugin anymore, there have been some breaking changes in that version that affected other plugins too.
