### ISSUE TITLE
Deploy in AWS CodeBuild doesn't wait for build completion

### ISSUE THREAD

**Issue by tobinbc** [serverless-heaven/serverless-webpack#654]
# This is a (Bug Report )

## Description

For bug reports:
* What went wrong?
Running `sls deploy` in AWS Codebuild, codebuild "finished" the command and moved on before webpack has finished.
* What did you expect should have happened?
The same as running the command locally; webpack finishes.
* What was the config you used?
* What stacktrace or error message from your provider did you see?
Lines omitted for brevity;
```

[Container] 2020/10/26 16:47:58 Running command npm -v
6.14.4
[Container] 2020/10/26 16:47:58 Running command node -v
v12.18.0
[Container] 2020/10/26 15:55:20 Running command (cd abcdef && npm i && SLS_DEBUG=* npm run deploy-$STAGE -- --force && echo done)
...

271 | Serverless: Invoke deploy
218 | Serverless: Invoke package
219 | Serverless: Invoke aws:common:validate
220 | Serverless: Invoke aws:common:cleanupTempDir
221 | Serverless: Invoke webpack:validate
222 | Serverless: Invoke webpack:compile
223 | Serverless: Bundling with Webpack...
224 | Starting type checking service...
225 | Starting type checking service...
226 | Starting type checking service...
227 | Starting type checking service...
228 | Starting type checking service...
229 | Starting type checking service...
230 | done
231 |  
232 | [Container] 2020/10/26 15:57:02 Running command echo abcdef Build ended `date`

```

It seems to wait about the same amount of time that I would expect between L229 and L230, but on a local Terminal we would see the webpack output and subsequent deployment. In the CodeBuild case, the command just completes and moves on.

My interpretation is that webpack is starting new shell processes that codebuild is not recognising as running. What do you think?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):

## Additional Data
        "serverless": "^1.61.2",
        "serverless-iam-roles-per-function": "^2.0.2",
        "serverless-prune-plugin": "^1.4.2",
        "serverless-pseudo-parameters": "^2.5.0",
        "serverless-webpack": "^5.3.1",
        "typescript": "^3.8.3",
        "webpack": "^4.43.0"
* ***Serverless-Webpack Version you're using***:  ^5.3.1
* ***Webpack version you're using***: ^4.43.0
* ***Serverless Framework Version you're using***: ^1.61.2   <-- this is because the later v2.5.x is erroring with `serverless-iam-roles-per-function`, and another project is using `serverless-aws-alias` which needs `^1.61.2` to deploy the first time, so we are keeping the same throughout. Bringing to the latest versions results in a `packageError` in `serverless-iam-roles-per-function`. This combination of versions appears stable.
* ***Operating System***: linux
* ***Stack Trace (if available)***:

**Comment by j0k3r** [comment]
This is really weird. Webpack doesn't start an other shell process.
Can you split the whole command `cd abcdef && npm i && SLS_DEBUG=* npm run deploy-$STAGE -- --force && echo done` into one on each line?
Also what the real script launched behind `deploy-$STAGE`?
I think `SLS_DEBUG=* npm run deploy-$STAGE -- --force` fail but as you chain it with `&& echo done` you got a silent error.

**Comment by tobinbc** [comment]
Thanks for the thoughts; I've had a go.

buildspec.yml
```
build:
    commands:
      - echo Entered the build phase...
      - echo abcdef Build started `date`
      # - (cd abcdef && npm i && SLS_DEBUG=* npm run deploy-$STAGE -- --force && echo done)
      - cd abcdef
      - npm i
      - SLS_DEBUG=* npm run deploy-dev
      - echo abcdef Build ended `date`

```

And logs:
```

103 | [Container] 2020/10/27 14:48:27 Running command echo abcdef Build started `date`
104 | abcdef Build started Tue Oct 27 14:48:27 UTC 2020
105 |  
106 | [Container] 2020/10/27 14:48:27 Running command cd abcdef
107 |  
108 | [Container] 2020/10/27 14:48:27 Running command npm i


144 | [Container] 2020/10/27 14:48:54 Running command SLS_DEBUG=* npm run deploy-dev
145 |  
146 | > truelayer@1.0.0 deploy-dev /codebuild/output/src413154376/src/pangolin
147 | > serverless deploy


214 | Serverless: Invoke deploy
215 | Serverless: Invoke package
216 | Serverless: Invoke aws:common:validate
217 | Serverless: Invoke aws:common:cleanupTempDir
218 | Serverless: Invoke webpack:validate
219 | Serverless: Invoke webpack:compile
220 | Serverless: Bundling with Webpack...
221 | Starting type checking service...
222 | Starting type checking service...
223 | Starting type checking service...
224 | Starting type checking service...
225 | Starting type checking service...
226 | Starting type checking service...
227 |  
228 | [Container] 2020/10/27 14:51:15 Running command echo abcdef Build ended `date`
229 | abcdef Build ended Tue Oct 27 14:51:15 UTC 2020
230 |  
231 | [Container] 2020/10/27 14:51:15 Phase complete: BUILD State: SUCCEEDED

```

It's definitely confusing; running locally in Terminal will work as expected.

**Comment by ambi-ly** [comment]
Seeing the same issue with CircleCI as well for serverless services with longer bundle time. Deploys without any issue in Terminal.

**Comment by ambi-ly** [comment]
Seeing the same issue with CircleCI. It is only seen in serverless services with longer bundle time (70s).
Deploys without any issue in Terminal using the same command.

#### In CD (CircleCI)
<img width="541" alt="Screen Shot 2020-11-12 at 1 14 12 PM" src="https://user-images.githubusercontent.com/8083914/98997188-f799da80-24e8-11eb-8b7c-b1d4caf117b9.png">

#### Deployment via Terminal
<img width="575" alt="Screen Shot 2020-11-12 at 1 13 47 PM" src="https://user-images.githubusercontent.com/8083914/98997151-e81a9180-24e8-11eb-8f5f-343830441beb.png">

**Comment by ambi-ly** [comment]
Figured out the issue in our case.
We are using the (Fork TS Checker Webpack Plugin)[https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#readme] and it was out of memory (4GB was not sufficient) and allocate more to the CircleCI container worked. The ForkTsCheckerWebpackPlugin is silently erroring out it seems.

If you don’t individually pack your functions, that will help too.

**Comment by ambi-ly** [comment]
Figured out the issue in our case.
We are using the [Fork TS Checker Webpack Plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#readme) and it was out of memory (4GB was not sufficient) and allocate more to the CircleCI container worked. The ForkTsCheckerWebpackPlugin is silently erroring out when memory is not sufficient it seems.

If you don’t individually pack your functions, that will help too.

**Comment by ambi-ly** [comment]
Figured out the issue in our case.

We are using the [Fork TS Checker Webpack Plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#readme) and it was out of memory as it does not limit the number of concurrent functions it run. After allocating more to the CircleCI container it worked.

Concurrency limit can be added using [this plugin](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin-limiter).

The `ForkTsCheckerWebpackPlugin` is silently erroring out when memory is not sufficient it seems. Similar issue ([link](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/441)) has been reported when you have many functions in the serverless.

(Update: Not reporting plugin failure is [deliberate](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/167) design.

If you don’t individually pack your functions, that will help too.

**Comment by tobinbc** [comment]
@ambi-ly Amazing thank you for finding this. Exactly the same issue for CodeBuild.
