### ISSUE TITLE
serverless-webpack support for new container image features in AWS Lambda and serverless

### ISSUE THREAD

**Issue by rogersgt** [serverless-heaven/serverless-webpack#698]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
AWS Lambda and subsequently the `serverless` organization announced support for Docker containers as custom runtimes. See [the serverless documentation](https://www.serverless.com/blog/container-support-for-lambda). It currently does not seem that `serverless-webpack` supports these new configuration options for your `serverless.yml`. When attempting to add an `image` property to a function definition with a `handler` property the following error is thrown:
![Screen Shot 2021-03-04 at 1 19 58 PM](https://user-images.githubusercontent.com/14983357/110010468-5380ad00-7cec-11eb-9821-04705b62d053.png)
After removing the `handler` property and only relying on `image.command` the following error is thrown:
![Screen Shot 2021-03-04 at 1 21 44 PM](https://user-images.githubusercontent.com/14983357/110010689-92aefe00-7cec-11eb-9394-5e798f19d47a.png)

* If there is additional config how would it look
According to the serverless docs above, we should be able to define our handler functions as what I assume would normally be the first argument to the `entryPoint` command.
![Screen Shot 2021-03-04 at 1 23 00 PM](https://user-images.githubusercontent.com/14983357/110010859-bffbac00-7cec-11eb-9d32-95e3d18b014b.png)

Similar or dependent issue(s):
* #12345

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.5
* ***Webpack version you're using***: 4.44.2
* ***Serverless Framework Version you're using***: 2.28.7
* ***Operating System***: OSX 11.1
* ***Stack Trace (if available)***:

**Comment by rogersgt** [comment]
I'd be happy to open a PR if I'm granted write permissions to push a feature branch up, or given some instructions how I might contribute. My company is leveraging this plugin and would love to see this feature added.

**Comment by master-of-null** [comment]
Would love to see this added.

**Comment by master-of-null** [comment]
Was able to circumvent by removing `package.individually: true`
