### ISSUE TITLE
[Deployment(in aws) in bitbucket pipeline using serverless]Error: EIO: i/o error chmod

### ISSUE THREAD

**Issue by himharsh1997** [serverless-heaven/serverless-webpack#745]
# This is a (Bug Report / Feature Proposal)
  Bug

## Description
I can't share the serverless.yml file but can share you error I try to deploy from docker in local with Node Version: 12.20.1
The below error coming at a time of build made in .webpack before zip made in .serverless folder to upload in s3.
Error: EIO: i/o error, chmod '/folder/.webpack/getDataQuery/node_modules/regenerator-runtime/README.md'

## Additional Data

* ***Serverless-Webpack Version you're using***: v5.2.0
* ***Webpack version you're using***: ^4.29.0
* ***Serverless Framework Version you're using***: 2.17.0
* ***Operating System***: Linux
* ***Stack Trace (if available)***:  Error: EIO: i/o error, chmod '/folder/.webpack/getDataQuery/node_modules/regenerator-runtime/README.md'

**Comment by j0k3r** [comment]
Without anything to check or see, it's barely impossible to fix..
