### ISSUE TITLE
Directory names that start with a dot are not being included in the zip file e.g. .nuxt

### ISSUE THREAD

**Issue by tihsin** [serverless-heaven/serverless-webpack#754]
# This is a Bug Report

## Description
We've been using serverless-webpack to deploy AWS Lambda Functions that run the Nuxt.js SSR renderer. The nuxt build outputs are included in the package using the package.include property of the function in the serverless.yml file.
With the current latest version on npm (5.4.0), directory names that begin with a dot e.g. `.nuxt` are not being included in the package zip file. The directory can be seen in the temporary `.webpack`  directory while the serverless packaging is running, but is not present in the final zip file. 
In our case, Nuxt expects to find the .nuxt/dist dir to be included with the code. This issue does not happen in versions 5.3.5 and earlier.

For bug reports:
* What went wrong?
The package zip file / uploaded package does not included directories if the name starts with `.`, e.g. `.nuxt`. Issue is not specific to this name alone, can recreate with '.something', but include works fine if the dir is named _nuxt or _something.

* What did you expect should have happened?
The zip file should include all directories that were included in the Serverless config.

* What was the config you used?
```
ssr-renderer:
    handler: functions/ssr-renderer.handler
    ...
    package:
        include:
            - .nuxt/**
            - config/**
```

* What stacktrace or error message from your provider did you see?
n/a, don't see any errors from Serverless during deploy / package.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.4.0
* ***Webpack version you're using***: 4.46.0
* ***Serverless Framework Version you're using***: 2.31.0
* ***Operating System***: Windows & latest Ubuntu image on AWS CodeBuild
* ***Stack Trace (if available)***:  n/a

**Comment by j0k3r** [comment]
Isn't the same as #744?

**Comment by tihsin** [comment]
Yes, seems the be the same issue. Sorry for the duplicate, the title and error there seemed unrelated while I was looking for similar issues to mine.

**Comment by j0k3r** [comment]
You're right, I've renamed it, thanks!
