### ISSUE TITLE
CLI 'type' option not predefined

### ISSUE THREAD

**Issue by bbarrington42** [serverless-heaven/serverless-webpack#764]
This is a Bug Report

## Description 

For bug reports:
* What went wrong?
  Warning is reported when I run sls
* What did you expect should have happened?
  No warning should be reported
* What was the config you used?
{
  "webpackConfig": "webpack.config.js",
  "includeModules": false,
  "packager": "npm",
  "packagerOptions": {},
  "keepOutputDirectory": false,
  "concurrency": 12
}

* What stacktrace or error message from your provider did you see?
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessWebpack for "out"

## Additional Data

* ***Serverless-Webpack Version you're using***:
  "serverless-webpack": "^5.4.0",
* ***Webpack version you're using***:
 "webpack": "^5.28.0"
* ***Serverless Framework Version you're using***:
Framework Core: 2.33.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1

* ***Operating System***:
Windows 10
* ***Stack Trace (if available)***:

**Comment by j0k3r** [comment]
Related https://www.serverless.com/framework/docs/deprecations#cli-options-extensions-type-requirement
