### ISSUE TITLE
excludeRegex not excluding files

### ISSUE THREAD

**Issue by l1b3r** [serverless-heaven/serverless-webpack#776]
# This is a (Bug Report / ~~Feature Proposal~~)

## Description

For bug reports:
* What went wrong?
When running `sls package --verbose`,  `excludeRegex` option [added](612) in v5.4.0 seems to be ignoring the regex and still adds all files to the output zip files.

* What did you expect should have happened?
Files that match `excludeRegex` should be excluded from the packaged zip files.

* What was the config you used?
```typescript
webpack: {
            keepOutputDirectory: true,
            excludeRegex: /\.ts|test|\.map/
        }
```
(I'm using `serverless.ts` instead of `serverless.yml` but that shouldn't matter I believe)

* What stacktrace or error message from your provider did you see?
`sls package --verbose` does not throw any explicit errors.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):
* [Initial implementation](612)

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.4.1
* ***Webpack version you're using***: 5.6.0
* ***Serverless Framework Version you're using***: 2.10.0
* ***Operating System***: Windows 10
* ***Stack Trace (if available)***:

**Comment by chaoyangnz** [comment]
not working, just debug into `packageModules.js` where files in filters, but not passed into the zip args.
