### ISSUE TITLE
different sha256sum for zip file when no code changes

### ISSUE THREAD

**Issue by chaoyangnz** [serverless-heaven/serverless-webpack#881]
# This is a Bug Report

## Description

I run serverless package twice without any changes in code and config. The I got the two zip files, when I compare them hash and found the hash is different.

serverless itself DO set the access and creation timestamp to 1970.01.01, but this plugin not.

## Additional Data

* ***Serverless-Webpack Version you're using***: 
5.5.1
* ***Webpack version you're using***:
4.42.0
* ***Serverless Framework Version you're using***:
2.23.0
* ***Operating System***:
Linux or MacOS
* ***Stack Trace (if available)***:

**Comment by russell-dot-js** [comment]
@chaoyangnz here you go #911 911
