### ISSUE TITLE
Feature Proposal: Add flag for ignoring plugin when running Serverless Offline

### ISSUE THREAD

**Issue by domcorvasce** [serverless-heaven/serverless-webpack#889]
# This is a Feature Proposal

## Description

I propose a command-line flag that allows developers to ignore the plugin altogether when running Serverless Offline.
It is especially useful to speed up **hot reload** when you don't need to bundle stuff locally.
This flag is different from `--no-build` which just skips compilation, and uses the most recent bundle.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.5.1
* ***Webpack version you're using***: 5.38.1
* ***Serverless Framework Version you're using***: 2.48.0
* ***Operating System***: Ubuntu Linux
* ***Stack Trace (if available)***:

**Comment by j0k3r** [comment]
See https://github.com/serverless-heaven/serverless-webpack/pull/890#issuecomment-969069909
