### ISSUE TITLE
Why does serverless-webpack run yarn install for you?

### ISSUE THREAD

**Issue by russell-dot-js** [serverless-heaven/serverless-webpack#913]
# This is a Question

## Description

See: https://github.com/serverless-heaven/serverless-webpack/blob/master/lib/packagers/yarn.js

serverless-webpack currently runs yarn install (as well as npm install) for you, depending on packager config. However, I can't help but feel that this is a bit redundant. Wouldn't most CI workflows already have run install prior to running serverless webpack? If not, how would serverless webpack even be installed to be able to run the command itself?

This is an issue particularly because it breaks yarn PnP. Are you open to at least having a config to disable the install altogether?

**Comment by russell-dot-js** [comment]
Example fix: https://github.com/kingsmendv/serverless-webpack/commit/09108cadc30305a0d662ac4e5b1bdd0426953f1b

**Comment by russell-dot-js** [comment]
IMO it's not a great feature as it introduces behavior beyond the intention of the plugin (running webpack)... it should be up to developers/CI to install their deps the way they intend to - this functionality can force behavior that users don't want (e.g. breaking PNP)

What do you think about my fix.. should I PR it?

**Comment by LeonardKoch** [comment]
As a user of serverless-webpack for whom the automatic re-install has been an issue, a PR to add a no-install option would be very appreciated.

For me this has been a blocker in a monorepo where lerna is used to link interpackage dependencies. When serverless-webpack tries to reinstall, those dependencies are not available and it fails.

**Comment by j0k3r** [comment]
> What do you think about my fix.. should I PR it?

I'm ok with the PR (don't forget to update the README too)
So with the addition of `noInstall` in `packagerOptions`, it means, `yarn install` will never run. I suppose it's ok for you?

**Comment by russell-dot-js** [comment]
@LeonardKoch @j0k3r @jefshe PR is up: https://github.com/serverless-heaven/serverless-webpack/pull/987/files
