### ISSUE TITLE
TypeError: a is not a function

### ISSUE THREAD

**Issue by hgalipuri** [serverless-heaven/serverless-webpack#929]
I keep getting `TypeError: a is not a function` error in my Typescript project. If I use the code as standalone I do not see any errors.

Error I get is
`500 error TypeError: a is not a function
    at n (/var/task/src/functions/get-gradings/webpack:/serverless-typescript/src/libs/redshift/jdbc.ts:6:31)
    at n (/var/task/src/functions/get-gradings/webpack:/serverless-typescript/src/libs/redshift/getData.ts:5:28)`

My Code (jdbc.ts)
```
// import * as pg from 'pg'
const config = require('./params');

export const client = async (brand, query) => {
    const pg = require('pg');
    // console.log(brand, query, config(brand));
    const pool = new pg.Pool(config(brand));
    try {
        console.time('DB Call Time');

        const res = await pool.query(query);
        console.timeEnd('DB Call Time');
        return res.rows;
    }
    catch (err) {
        console.log('Error at DB Call  :::::::  ', err.stack);
        throw err;
    }

}
```

My current config

![image](https://user-images.githubusercontent.com/80979464/129141066-52e490d3-5b9e-4d12-9ffe-77ae9b233485.png)

Any help is appreciated. Thank you.

**Comment by pomSense** [comment]
@hgalipuri Did you end up resolving this? I'm stuck with the same issue of "_ is not a function"
