### ISSUE TITLE
Error: npm install failed with code 1 for installing bitbucket repository(typescipt project) as package in my ts project

### ISSUE THREAD

**Issue by himharsh1997** [serverless-heaven/serverless-webpack#955]
Error --------------------------------------------------
 
  Error: npm install failed with code 1
      at ChildProcess.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/serverless-webpack/lib/utils.js:91:16)
      at ChildProcess.emit (events.js:210:5)
      at ChildProcess.EventEmitter.emit (domain.js:475:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.14.0
     Framework Version:         2.17.0 (local)
     Plugin Version:            4.6.0
     SDK Version:               n/a
     Components Version:        3.17.0

```
  "serverless-webpack": "5.3.5",
  "webpack": "^4.29.0",
  "webpack-node-externals": "^1.7.2"
```

**Comment by j0k3r** [comment]
Could you update to latest `serverless-webpack` & `webpack`?
Could you also share your `serverless.yml`?

Also, don't remove stuff from the issue template, it avoid us asking common question like the two above ...

**Comment by himharsh1997** [comment]
Will update for both. 
**My points:**

1. - But when I try to deploy project from local using` sls deploy` the project got deployed successfully.
2. But when I try to deploy using bitbucket with node:12.14.0 it caused this error
3. In my typescript project I installing another typescript project(which having postinstall script 'tsc') inside node_modules.

**Comment by himharsh1997** [comment]
> Could you update to latest `serverless-webpack` & `webpack`?
> Could you also share your `serverless.yml`?
> 
> Also, don't remove stuff from the issue template, it avoid us asking common question like the two above ...

Not working for me when using these
```
  "serverless-webpack": "5.5.4",
    "webpack": "5.52.1",
```

**Comment by himharsh1997** [comment]
Could it be caused due to installed other typescript project as dependency in my project as last deployment was successful and after this change it giving this error??

**Comment by stupiginproducton** [comment]
@himharsh1997 I encountered the same error too after installed other private typescript package.

**Comment by chriszirkel** [comment]
I have the same issue running on a GitHub actions workflow. I think it's related to this issue: https://github.com/serverless-heaven/serverless-webpack/issues/781

The issue pops up on Node 14 and not on Node 16. I guess it's related to NPM v6 vs v7 and the output of the `npm ls -prod -json -depth=1` command thats being executed by serverless-webpack.

**Comment by afcode123** [comment]
I am having this exact issue when running sls deploy locally. Previously it was working fine, but now it fails on npm install. Any ideas how to fix it? 

```
asset src/apollo-server.js 236 KiB [emitted] (name: src/apollo-server)
orphan modules 103 KiB [orphan] 55 modules
runtime modules 937 bytes 4 modules
built modules 103 KiB [built]
  ./src/apollo-server.ts + 55 modules 103 KiB [not cacheable] [built] [code generated]
  external "fs" 42 bytes [built] [code generated]
  external "util" 42 bytes [built] [code generated]
webpack compiled successfully in 3897 ms
Serverless: Invoke webpack:package
Serverless: WARNING: Could not determine version of module jsonwebtoken
Serverless: WARNING: Could not determine version of module .prisma
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: reflect-metadata@^0.1.13, apollo-server-lambda@^3.3.0, graphql@^15.5.3, type-graphql@^1.1.1, class-validator@^0.13.1, jsonwebtoken, jwks-rsa@^2.0.5, @prisma/client@^2.30.0, graphql-fields@^2.0.3, uuid@^8.3.2, .prisma, axios@^0.21.4, dayjs@^1.10.7
 
 Error ---------------------------------------------------
 
  Error: npm install failed with code 1
      at ChildProcess.<anonymous> (<path>/node_modules/serverless-webpack/lib/utils.js:91:16)
      at ChildProcess.emit (events.js:210:5)
      at ChildProcess.EventEmitter.emit (domain.js:475:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         2.66.1 (local)
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.0
 
```

**Comment by vicary** [comment]
@afcode123 `serverless-webpack` will try to create a single-use `package.json` and perform `npm install` with it, part of the reason is to ensure dependency completeness when you use `forceInclude` and `forceExclude`.

One common cause of this error comes from including or excluding packages which is not already installed in your root `package.json`.

**Comment by Arunaliyanaarachchi** [comment]
Delete packge-lock.JSON and node module folder. then npm install

**Comment by james-ingold** [comment]
Not sure if this will help anyone but was having the same issue in bitbucket with serverless@2. I downgraded my node image in the pipeline from 17.4 to 14.4 and deployed successfully without npm install failed with code 1 issue.

**Comment by moroine** [comment]
I faced this issue, and it's related to `npm install` command. Try to go in the `.webpack` and manually try `npm install`

**Comment by vicary** [comment]
I see this question in a constant rate. We can either piping the packager's stderr outwards, or simply document this behavior.

A PR is definitely appreciated.

**Comment by vishnu-buildd** [comment]
A much better error would be appreciated. I use a private package. My build fails, but deploy works. i.e. `sls package` fails while `sls deploy` works. I am not really sure how to even debug this better.

**Comment by mrjasan** [comment]
I'm having the same issue deploying on CircleCI

```
Package lock found - Using locked versions
Packing external modules: @aws-sdk/client-cloudwatch@^3.72.0, @aws-sdk/client-dynamodb@^3.72.0, @aws-sdk/lib-dynamodb@^3.72.0, @aws-sdk/smithy-client, @aws-sdk/types,  deepmerge

× Stack *******-prod failed to deploy (9s)
Environment: linux, node 12.20.2, framework 3.14.0, plugin 6.2.1, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: npm install failed with code 1
    at ChildProcess.<anonymous> (/home/circleci/app/node_modules/serverless-webpack/lib/utils.js:91:16)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by ViniciusAlberkovics** [comment]
Try to add the packager property in the serverless-webpack configuration informing the package manager used in the project. (npm|yarn).

Sample:
serverless.ts
```ts
  custom: {
    webpack: {
      webpackConfig: "./webpack.config.js",
      packager: "npm",
      includeModules: true,
    },
```

serverless.yml
```yml
custom:
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
     includeModules: true
```

**Comment by HaaLeo** [comment]
I have the [exact same issue as @mrjasan](https://github.com/serverless-heaven/serverless-webpack/issues/955#issuecomment-1101020834) when running `sls package` on AWS CodeBuild.

**Comment by ViniciusAlberkovics** [comment]
> 

I had the same issue with npm@8.11.0 in Azure DevOps Pipeline, I solved it by downgrading npm to version 8.10.0.

**Comment by HaaLeo** [comment]
Thx @ViniciusAlberkovics that fixed it for me.

**Comment by mrjasan** [comment]
Update - my issue was related to using a private package and not setting up the right credentials. Everything else worked fine after I fixed that.

**Comment by vicary** [comment]
Everyone is welcomed for contribution in either,
1. Piping error messages from the packager child process, or
2. Document this behavior and lead users to do a test install.

Please open a PR directly and ping us for reviewing.

But the plugin is working as expected, so I'll close for now.

Others may continue to add more scenarios in the comments to aid future contributors for the PR.

**Comment by AlexRRR** [comment]
@vicary  
> 1. Piping error messages from the packager child process, or
would you happen to know how to manually do this? I am having the same issue `npm install failed with code 1` described here but I am not able to tell the reason, does not seem to relate to what others have experienced. thanks!

**Comment by vicary** [comment]
@AlexRRR you would start from these two methods,

https://github.com/serverless-heaven/serverless-webpack/blob/6975610cccf87ce8f69389c74c8546de4123aabf/lib/packagers/yarn.js#L120-L140

https://github.com/serverless-heaven/serverless-webpack/blob/89c629e4d49ebdba5af9f69330f155df287d6506/lib/packagers/npm.js#L119-L128

Because `Util.spawnProcess` is already resolving with `stdout` and `stderr`, you only need to change the `.return()` and add to the logs in the following section.

https://github.com/serverless-heaven/serverless-webpack/blob/5d5723ea3ed1b97fbeebb79ddbeaaaeee7693404/lib/packExternalModules.js#L395-L402

**Comment by AlexRRR** [comment]
@vicary  thank you so much, with that I found out that my problem when running the `sls webpack` command on CI for external modules was related to our private npm repo which requires auth, since there was no `.npmrc´ setup on the `.webpack` directory it was no able to do the npm install, solved by copying the `.npmrc` file to the home directory of the user running the CI build.

it indeed would have been so much easier if the output was not swallowed by the child process, but again super grateful for your help!

**Comment by vrashankraom** [comment]
![image (1)](https://user-images.githubusercontent.com/54736823/201324306-946d76bb-5c69-4e73-9606-0fbbec288c89.png)

Try to press the clear runner cache at top, as seen in this image. This worked for me.
Note:- Only project maintainers has access to this button.

**Comment by ahmadysalah** [comment]
Dont delete package lock file after install dependancy or use yarn to install sls service

**Comment by adumat** [comment]
@AlexRRR and @vicary thanks, i've found that my failing was because yarn 2 in ci by default set YARN_ENABLE_IMMUTABLE_INSTALLS to true (that in my case is not exactly immutable "by design")

**Comment by apmechev** [comment]
same issue/resolution as @adumat, we migrated from npm to yarn and the package broke. Here's the config fix for us

```
---
  webpack:
    packager: "yarn"
    packagerOptions:
      noFrozenLockfile: true
---
```

**Comment by syn2ed** [comment]
> ![image (1)](https://user-images.githubusercontent.com/54736823/201324306-946d76bb-5c69-4e73-9606-0fbbec288c89.png)
> 
> Try to press the clear runner cache button at top, as seen in this image. This worked for me. Note:- Only project maintainers has access to this button.

This worked for me, thank you !
